const FRIDGE={model:'MR-JW52TJ',totalLiters:517,locations:[{id:'refrigerator-upper',name:'冷蔵室・上段',capacity:75},{id:'refrigerator-middle',name:'冷蔵室・中段',capacity:75},{id:'refrigerator-lower',name:'冷蔵室・下段',capacity:87},{id:'door',name:'ドアポケット',capacity:40},{id:'vegetable',name:'野菜室',capacity:98},{id:'ice',name:'製氷室',capacity:23},{id:'switch',name:'切替室',capacity:30},{id:'freezer',name:'冷凍室',capacity:89}]};
const RULES=[{words:['牛乳','豆腐'],category:'乳製品・日配',cold:5,frozen:30},{words:['豚','牛肉','鶏','ひき肉','肉'],category:'肉類',cold:3,frozen:30},{words:['魚','鮭','刺身'],category:'魚介類',cold:2,frozen:21},{words:['キャベツ','白菜','にんじん','大根','玉ねぎ','野菜'],category:'野菜',cold:10,frozen:30},{words:['卵'],category:'卵',cold:14,frozen:30},{words:['ヨーグルト'],category:'乳製品',cold:7,frozen:21},{words:['しょうゆ','味噌','マヨネーズ','ケチャップ','ソース','ドレッシング','めんつゆ','ポン酢','みりん','料理酒','酢','わさび','からし'],category:'調味料',cold:60,frozen:90}];
const FOOD_PRESETS=[{name:'牛乳',aliases:['ぎゅうにゅう','ミルク'],liters:1.1,unit:'本'},{name:'キャベツ',aliases:['きゃべつ','甘藍'],liters:5,unit:'個'},{name:'白菜',aliases:['はくさい'],liters:6,unit:'個'},{name:'玉ねぎ',aliases:['たまねぎ','タマネギ','玉葱'],liters:.6,unit:'個'},{name:'にんじん',aliases:['ニンジン','人参'],liters:.5,unit:'本'},{name:'大根',aliases:['だいこん','ダイコン'],liters:2.5,unit:'本'},{name:'レタス',aliases:['れたす','萵苣'],liters:4,unit:'個'},{name:'トマト',aliases:['とまと','蕃茄'],liters:.5,unit:'個'},{name:'きゅうり',aliases:['キュウリ','胡瓜'],liters:.35,unit:'本'},{name:'じゃがいも',aliases:['ジャガイモ','馬鈴薯','じゃが芋'],liters:.4,unit:'個'},{name:'豚こま肉',aliases:['ぶたこまにく','ブタコマニク','豚肉','ぶたにく','ブタニク'],liters:.8,unit:'パック'},{name:'牛肉',aliases:['ぎゅうにく','ギュウニク'],liters:.8,unit:'パック'},{name:'鶏肉',aliases:['とりにく','トリニク','鳥肉'],liters:1,unit:'パック'},{name:'ひき肉',aliases:['ひきにく','ヒキニク','挽肉','挽き肉'],liters:.7,unit:'パック'},{name:'鮭',aliases:['さけ','サケ','しゃけ','シャケ'],liters:.6,unit:'パック'},{name:'卵',aliases:['たまご','タマゴ','玉子'],liters:2,unit:'パック'},{name:'豆腐',aliases:['とうふ','トウフ'],liters:.5,unit:'パック'},{name:'ヨーグルト',aliases:['よーぐると'],liters:.5,unit:'個'},{name:'チーズ',aliases:['ちーず','乾酪'],liters:.35,unit:'パック'},{name:'納豆',aliases:['なっとう','ナットウ'],liters:.45,unit:'パック'},{name:'ジュース',aliases:['じゅーす','果汁飲料'],liters:1.1,unit:'本'},{name:'冷凍食品',aliases:['れいとうしょくひん','レイトウショクヒン'],liters:1,unit:'袋'}];
const CONDIMENT_PRESETS=[{name:'しょうゆ',aliases:['ショウユ','醤油'],liters:.7,unit:'本'},{name:'味噌',aliases:['みそ','ミソ'],liters:.8,unit:'個'},{name:'マヨネーズ',aliases:['まよねーず','マヨ'],liters:.5,unit:'本'},{name:'ケチャップ',aliases:['けちゃっぷ','トマトケチャップ'],liters:.5,unit:'本'},{name:'ソース',aliases:['そーす','ウスターソース','中濃ソース','とんかつソース'],liters:.6,unit:'本'},{name:'ドレッシング',aliases:['どれっしんぐ'],liters:.5,unit:'本'},{name:'めんつゆ',aliases:['メンツユ','麺つゆ','麺汁'],liters:.6,unit:'本'},{name:'ポン酢',aliases:['ぽんず','ポンズ','ぽん酢'],liters:.5,unit:'本'},{name:'みりん',aliases:['ミリン','味醂'],liters:1,unit:'本'},{name:'料理酒',aliases:['りょうりしゅ','リョウリシュ'],liters:1,unit:'本'},{name:'酢',aliases:['す','ス','食酢'],liters:.6,unit:'本'},{name:'わさび',aliases:['ワサビ','山葵'],liters:.15,unit:'本'},{name:'からし',aliases:['カラシ','辛子','芥子'],liters:.15,unit:'本'}];FOOD_PRESETS.push(...CONDIMENT_PRESETS);
const EXTRA_FOOD_PRESETS=[{name:'さば',aliases:['サバ','鯖'],liters:.7,unit:'パック'},{name:'まぐろ',aliases:['マグロ','鮪'],liters:.6,unit:'パック'},{name:'ぶり',aliases:['ブリ','鰤'],liters:.7,unit:'パック'},{name:'あじ',aliases:['アジ','鯵'],liters:.6,unit:'パック'},{name:'りんご',aliases:['リンゴ','林檎'],liters:.5,unit:'個'},{name:'バナナ',aliases:['ばなな','甘蕉'],liters:1,unit:'袋'},{name:'みかん',aliases:['ミカン','蜜柑'],liters:.35,unit:'個'}];FOOD_PRESETS.push(...EXTRA_FOOD_PRESETS);RULES.push({words:['りんご','バナナ','みかん','果物'],category:'果物',cold:10,frozen:30});
const QUICK_CATEGORIES=[{id:'meat',name:'肉',mark:'肉類',foods:['豚こま肉','牛肉','鶏肉','ひき肉']},{id:'fish',name:'魚',mark:'魚介',foods:['鮭','さば','まぐろ','ぶり','あじ']},{id:'vegetable',name:'野菜',mark:'野菜',foods:['キャベツ','白菜','玉ねぎ','にんじん','大根','レタス','トマト','きゅうり','じゃがいも']},{id:'fruit',name:'果物',mark:'果物',foods:['りんご','バナナ','みかん']},{id:'dairy',name:'乳製品',mark:'乳製品',foods:['牛乳','ヨーグルト','チーズ']},{id:'daily',name:'卵・日配',mark:'卵日配',foods:['卵','豆腐','納豆']},{id:'seasoning',name:'調味料',mark:'調味料',foods:['しょうゆ','味噌','マヨネーズ','ケチャップ','ソース','ドレッシング','めんつゆ','ポン酢']},{id:'frozen',name:'冷凍食品',mark:'冷凍品',foods:['冷凍食品']}];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function readStoredItems(fallback=[]){try{const raw=localStorage.getItem('fridge-items')||localStorage.getItem('fridgeItems')||localStorage.getItem('fridgeInventory');if(!raw)return fallback;const parsed=JSON.parse(raw);if(Array.isArray(parsed))return parsed;if(Array.isArray(parsed?.items))return parsed.items;return fallback}catch{return fallback}}
function readStoredObject(key){try{const parsed=JSON.parse(localStorage.getItem(key)||'{}');return parsed&&typeof parsed==='object'&&!Array.isArray(parsed)?parsed:{}}catch{return{}}}
let items=readStoredItems();let barcodeCache=readStoredObject('fridge-barcode-cache');let customCategoryFoods=readStoredObject('fridge-custom-foods');let activeQuickCategory='';let deletingCustomFood=false;let currentStep=1;let activeMapLocations=[];let pendingLocation='';let pendingBarcode='';let pendingExpiryDate='';let pendingExpiryKind='';let barcodeStream=null;let expiryStream=null;let barcodeTimer=null;let barcodeControls=null;
const iso=d=>{const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)};
const addDays=(date,n)=>{const d=new Date(date);d.setDate(d.getDate()+n);return iso(d)};
let editingItemId='';
function normalizeFoodText(value){return String(value||'').normalize('NFKC').toLowerCase().replace(/[ァ-ヶ]/g,char=>String.fromCharCode(char.charCodeAt(0)-0x60)).replace(/[\s・ー]/g,'')}
function ruleFor(name){const normalizedNames=[name,presetFor(name).name].map(normalizeFoodText);return RULES.find(rule=>rule.words.some(word=>normalizedNames.some(value=>value.includes(normalizeFoodText(word)))))||{category:'その他',cold:7,frozen:30}}
function presetFor(name){const normalized=normalizeFoodText(name);return FOOD_PRESETS.find(food=>[food.name,...food.aliases].some(word=>normalized.includes(normalizeFoodText(word))))||{name:'その他',liters:1,unit:'個'}}
function itemLiters(item){return Number(item.volumeLiters??presetFor(item.name).liters)*Number(item.quantity||1)}
function showStep(n){currentStep=n;$$('.form-step').forEach((e,i)=>e.classList.toggle('active',i===n-1));$$('.step').forEach((e,i)=>e.classList.toggle('current',i===n-1));if(n===3){prepareFinalStep();const preferred=$(`input[name="location"][value="${pendingLocation}"]`);if(preferred){preferred.checked=true;preferred.dispatchEvent(new Event('change'))}if(pendingExpiryDate){$('#expiryDate').value=pendingExpiryDate;$('#expiryHint').textContent=`バーコード入力で確認した${pendingExpiryKind||'期限'}です。日付を再確認してください。`}}}
function prepareFinalStep(){const storage=$('input[name="storage"]:checked').value;const cold=storage==='冷蔵';const rooms=cold?[['refrigerator-upper','上段'],['refrigerator-middle','中段'],['refrigerator-lower','下段'],['door','ドアポケット'],['vegetable','野菜室']]:[['switch','切替室'],['freezer','冷凍室']];const option=(id,label,extra='')=>`<label class="map-location-option ${extra}"><input type="radio" name="location" value="${id}" ${id===rooms[0][0]?'checked':''}><span><b>${label}</b><small>${FRIDGE.locations.find(x=>x.id===id)?.capacity||''}L</small></span></label>`;$('#locationChoices').innerHTML=`<div class="location-map-title"><b>MR-JW52TJ</b><small>${storage}できる場所を表示しています</small></div><div class="location-fridge ${cold?'cold-mode':'frozen-mode'}">${cold?`<div class="open-fridge"><div class="shelf-column">${option('refrigerator-upper','冷蔵室・上段','shelf upper')}${option('refrigerator-middle','冷蔵室・中段','shelf middle')}${option('refrigerator-lower','冷蔵室・下段','shelf lower')}</div>${option('door','ドアポケット','open-door')}</div><div class="closed-pair"><div class="disabled-room">製氷室</div><div class="disabled-room">切替室</div></div><div class="disabled-room wide">冷凍室</div>${option('vegetable','野菜室','wide-room')}`:`<div class="disabled-room tall">冷蔵室</div><div class="closed-pair"><div class="disabled-room">製氷室</div>${option('switch','切替室','compact-room')}</div>${option('freezer','冷凍室','wide-room freezer-choice')}<div class="disabled-room wide">野菜室</div>`}</div><p id="selectedLocation" class="selected-location"></p>`;const update=()=>{const selected=$('input[name="location"]:checked');$('#selectedLocation').textContent=`選択中：${FRIDGE.locations.find(x=>x.id===selected.value)?.name}`};$$('input[name="location"]').forEach(input=>input.onchange=update);update();const rule=ruleFor($('#itemName').value.trim());const days=storage==='冷凍'?rule.frozen:rule.cold;$('#expiryDate').value=addDays($('#purchaseDate').value,days);$('#expiryHint').textContent=`「${rule.category}・${storage}」の一般的な目安として購入日から${days}日後を提案しています。表示や状態を優先して変更してください。`}
function save(){localStorage.setItem('fridge-items',JSON.stringify(items));render();renderQuickPicker()}
function refreshStoredItems(){items=readStoredItems(items);$('#itemCount').textContent=items.length;render()}
function remaining(item){return Math.ceil((new Date(item.expiry+'T23:59:59')-new Date())/86400000)}
function card(item){const days=remaining(item),status=days<0?`${Math.abs(days)}日超過`:days===0?'今日まで':`あと${days}日`,place=FRIDGE.locations.find(x=>x.id===item.location)?.name||item.location;return `<article class="item-card compact-item-card"><div class="item-compact-line item-compact-main"><div class="item-identity"><span class="tag">${escapeHtml(item.category)}</span><strong>${escapeHtml(item.name)}</strong><span>${item.quantity}${escapeHtml(item.unit)}・${item.storage}</span></div><div class="item-card-actions"><button class="edit" data-edit="${item.id}" aria-label="編集">編集</button><button class="delete" data-delete="${item.id}" aria-label="削除">削除</button></div></div><div class="item-compact-line item-compact-sub"><span>${escapeHtml(place)}</span><span class="expiry ${days<0?'overdue':days<=3?'soon':''}">${status}（${item.expiry}）</span></div></article>`}
function roomUsage(locations){return items.filter(item=>locations.includes(item.location)).reduce((sum,item)=>sum+itemLiters(item),0)}
function roomCapacity(locations){return locations.reduce((sum,id)=>sum+(FRIDGE.locations.find(room=>room.id===id)?.capacity||0),0)}
function renderMap(){$$('.map-items').forEach(area=>{const locations=area.dataset.mapItems.split(','),stored=items.filter(item=>locations.includes(item.location)),used=roomUsage(locations),capacity=roomCapacity(locations),percent=Math.min(100,used/capacity*100);area.innerHTML=`<span class="room-capacity">${used.toFixed(1)} / ${capacity}L（残り${Math.max(0,capacity-used).toFixed(1)}L）</span><span class="mini-meter"><i style="width:${percent}%"></i></span>`+(stored.length?stored.slice(0,4).map(item=>`<span class="map-item">${item.name}</span>`).join('')+(stored.length>4?`<span class="map-item">ほか${stored.length-4}件</span>`:''):'<span class="map-empty">空</span>')});$$('.compartment').forEach(room=>{const locations=room.dataset.mapLocation.split(',');room.classList.toggle('selected',activeMapLocations.length>0&&locations.some(id=>activeMapLocations.includes(id)));room.onclick=()=>{activeMapLocations=locations;$('#filterLocation').value=locations.length===1?locations[0]:'';render()}});const action=$('#mapAddAction');action.hidden=!activeMapLocations.length;if(activeMapLocations.length){$('#mapAddPlace').textContent=activeMapLocations.length===1?FRIDGE.locations.find(room=>room.id===activeMapLocations[0])?.name:'冷蔵室（棚は登録時に選択）'}$('#clearLocation').onclick=()=>{activeMapLocations=[];$('#filterLocation').value='';render()}}
function render(){const q=$('#searchInput').value.toLowerCase(),loc=$('#filterLocation').value,locations=activeMapLocations.length?activeMapLocations:(loc?[loc]:[]);const filtered=items.filter(x=>x.name.toLowerCase().includes(q)&&(!locations.length||locations.includes(x.location)));$('#inventoryList').innerHTML=filtered.length?filtered.map(card).join(''):'<div class="empty">この場所には食材がありません。</div>';const place=locations.length===1?FRIDGE.locations.find(x=>x.id===locations[0])?.name:locations.length?'冷蔵室（各段）':'冷蔵庫全体';$('#inventorySummary').textContent=`${place}：${filtered.length}件`;const alerts=items.filter(x=>remaining(x)<=3).sort((a,b)=>remaining(a)-remaining(b));$('#alertList').innerHTML=alerts.length?alerts.map(card).join(''):'<div class="empty">3日以内の期限リマインドはありません。</div>';$('#itemCount').textContent=items.length;$('#alertCount').textContent=alerts.length;const liters=Math.min(FRIDGE.totalLiters,items.reduce((n,x)=>n+itemLiters(x),0));$('#capacityText').textContent=`${liters.toFixed(1)} / ${FRIDGE.totalLiters} L`;$('#capacityBar').style.width=`${liters/FRIDGE.totalLiters*100}%`;renderMap()}
function navigate(view){$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$$('.view').forEach(x=>x.classList.remove('active'));$(`#${view}View`).classList.add('active');$('#pageTitle').textContent={add:'何を追加しますか？',inventory:'冷蔵庫の中身',alerts:'期限リマインド'}[view];render()}
$$('.next').forEach(b=>b.onclick=()=>{if(currentStep===1&&!$('#itemName').value.trim()){ $('#itemName').reportValidity();return}showStep(currentStep+1)});$$('.back').forEach(b=>b.onclick=()=>showStep(currentStep-1));$$('.nav').forEach(b=>b.onclick=()=>navigate(b.dataset.view));
$('#itemForm').onsubmit=e=>{e.preventDefault();const name=$('#itemName').value.trim(),rule=ruleFor(name);items.unshift({id:globalThis.crypto?.randomUUID?.()||`item-${Date.now()}-${Math.random().toString(16).slice(2)}`,name,category:rule.category,quantity:$('#quantity').value,unit:$('#unit').value,volumeLiters:Number($('#volume').value),storage:$('input[name="storage"]:checked').value,location:$('input[name="location"]:checked').value,purchased:$('#purchaseDate').value,expiry:$('#expiryDate').value,createdAt:new Date().toISOString()});pendingLocation='';save();e.target.reset();$('#quantity').value=1;$('#volume').value=1;$('#purchaseDate').value=iso(new Date());showStep(1);const t=$('#toast');t.textContent=`${name}を追加しました`;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200);navigate('inventory')};
function editLocationOptions(storage,selected){const allowed=storage==='冷凍'?['switch','freezer']:['refrigerator-upper','refrigerator-middle','refrigerator-lower','door','vegetable'];return FRIDGE.locations.filter(room=>allowed.includes(room.id)).map(room=>`<option value="${room.id}" ${room.id===selected?'selected':''}>${room.name}</option>`).join('')}
function openItemEditor(id){const item=items.find(entry=>entry.id===id);if(!item)return;editingItemId=id;$('#editItemName').value=item.name;$('#editQuantity').value=item.quantity;$('#editUnit').value=item.unit;$('#editStorage').value=item.storage;$('#editLocation').innerHTML=editLocationOptions(item.storage,item.location);$('#editExpiry').value=item.expiry;$('#editItemDialog').showModal()}
document.addEventListener('click',e=>{const editId=e.target.dataset.edit;if(editId){openItemEditor(editId);return}const id=e.target.dataset.delete;if(id&&confirm('この食材を削除しますか？')){items=items.filter(x=>x.id!==id);save()}});$('#searchInput').oninput=render;$('#filterLocation').onchange=()=>{activeMapLocations=$('#filterLocation').value?[$('#filterLocation').value]:[];render()};
$('#editStorage').onchange=()=>{$('#editLocation').innerHTML=editLocationOptions($('#editStorage').value,'')};$('#closeEditItem').onclick=$('#cancelEditItem').onclick=()=>$('#editItemDialog').close();$('#editItemForm').onsubmit=event=>{event.preventDefault();const index=items.findIndex(item=>item.id===editingItemId);if(index<0)return;const name=$('#editItemName').value.trim(),preset=presetFor(name),rule=ruleFor(name);items[index]={...items[index],name,category:rule.category,quantity:$('#editQuantity').value,unit:$('#editUnit').value,volumeLiters:preset.liters,storage:$('#editStorage').value,location:$('#editLocation').value,expiry:$('#editExpiry').value};save();$('#editItemDialog').close();const toast=$('#toast');toast.textContent=`${name}の内容を更新しました`;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)};
$('#addToSelectedRoom').onclick=()=>{pendingLocation=activeMapLocations.length===1?activeMapLocations[0]:'';const frozen=['freezer','switch'].includes(pendingLocation);$(`input[name="storage"][value="${frozen?'冷凍':'冷蔵'}"]`).checked=true;showStep(1);navigate('add');setTimeout(()=>$('#itemName').focus(),0)};
function applyFoodPreset(name){const food=presetFor(name);$('#volume').value=food.liters;$('#unit').value=[...$('#unit').options].some(option=>option.value===food.unit)?food.unit:$('#unit').value}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function foodIconButton(name){const safe=escapeHtml(name);return`<button type="button" class="food-icon-button" data-quick-food="${safe}"><span class="food-pictogram" aria-hidden="true">${escapeHtml(name.slice(0,3))}</span><b>${safe}</b></button>`}
function deleteChoiceButton(name){const safe=escapeHtml(name);return`<button type="button" class="food-icon-button delete-choice" data-remove-choice="${safe}"><span class="food-pictogram" aria-hidden="true">${escapeHtml(name.slice(0,3))}</span><b>${safe}</b></button>`}
function selectQuickFood(name){$('#itemName').value=name;applyFoodPreset(name);showStep(1);$('#itemForm').scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>$('#quantity').focus(),350)}
function foodsForCategory(category){return[...category.foods,...(customCategoryFoods[category.id]||[])]}
function openQuickCategory(id){const category=QUICK_CATEGORIES.find(item=>item.id===id);if(!category)return;activeQuickCategory=id;deletingCustomFood=false;$$('[data-quick-category]').forEach(button=>button.classList.toggle('selected',button.dataset.quickCategory===id));$('#selectedCategoryName').textContent=`${category.name}から選ぶ`;$('#categoryFoods').innerHTML=foodsForCategory(category).map(foodIconButton).join('');$('#customFoodName').placeholder=`${category.name}の食材名`;$('#customFoodForm').hidden=false;$('#manageCustomFoods').textContent='削除';const panel=$('#categoryFoodsPanel');panel.hidden=false;requestAnimationFrame(()=>panel.scrollIntoView({behavior:'smooth',block:'nearest'}))}
function showCustomFoodDeleteMode(){const foods=customCategoryFoods[activeQuickCategory]||[];if(!foods.length){const toast=$('#toast');toast.textContent='削除できる追加食材はありません';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200);return}deletingCustomFood=true;$('#selectedCategoryName').textContent='削除する食材を選択';$('#categoryFoods').innerHTML=foods.map(deleteChoiceButton).join('');$('#customFoodForm').hidden=true;$('#manageCustomFoods').textContent='キャンセル'}
function renderQuickPicker(){$('#categoryGrid').innerHTML=QUICK_CATEGORIES.map(category=>`<button type="button" class="category-icon-button" data-quick-category="${category.id}"><span class="category-pictogram" aria-hidden="true">${category.mark}</span><b>${category.name}</b></button>`).join('')}
$('#categoryGrid').onclick=event=>{const button=event.target.closest('[data-quick-category]');if(button)openQuickCategory(button.dataset.quickCategory)};$('#categoryFoods').onclick=event=>{const removeChoice=event.target.closest('[data-remove-choice]');if(removeChoice){const name=removeChoice.dataset.removeChoice;if(!confirm(`「${name}」を削除しますか？`))return;customCategoryFoods[activeQuickCategory]=(customCategoryFoods[activeQuickCategory]||[]).filter(food=>food!==name);localStorage.setItem('fridge-custom-foods',JSON.stringify(customCategoryFoods));openQuickCategory(activeQuickCategory);const toast=$('#toast');toast.textContent=`${name}を削除しました`;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200);return}const button=event.target.closest('[data-quick-food]');if(button)selectQuickFood(button.dataset.quickFood)};
$('#manageCustomFoods').onclick=()=>deletingCustomFood?openQuickCategory(activeQuickCategory):showCustomFoodDeleteMode();
$('#customFoodForm').onsubmit=event=>{event.preventDefault();const name=$('#customFoodName').value.trim();if(!name||!activeQuickCategory)return;const category=QUICK_CATEGORIES.find(item=>item.id===activeQuickCategory),foods=foodsForCategory(category);if(foods.some(food=>normalizeFoodText(food)===normalizeFoodText(name))){const toast=$('#toast');toast.textContent='同じ食材がすでにあります';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200);return}customCategoryFoods[activeQuickCategory]=[...(customCategoryFoods[activeQuickCategory]||[]),name];localStorage.setItem('fridge-custom-foods',JSON.stringify(customCategoryFoods));$('#customFoodName').value='';openQuickCategory(activeQuickCategory);const toast=$('#toast');toast.textContent=`${name}をカテゴリに追加しました`;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)};
$('#closeCategoryFoods').onclick=()=>$('#categoryFoodsPanel').hidden=true;$('#showManualEntry').onclick=()=>{$('#itemForm').scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>$('#itemName').focus(),350)};
function loadOcr(){if(globalThis.Tesseract)return Promise.resolve(globalThis.Tesseract);return new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';script.onload=()=>resolve(globalThis.Tesseract);script.onerror=reject;document.head.appendChild(script)})}
$('#itemName').oninput=()=>applyFoodPreset($('#itemName').value);$('#foodSuggestions').innerHTML=FOOD_PRESETS.map(food=>`<option value="${food.name}"></option>`).join('');

function stopBarcode(){clearInterval(barcodeTimer);barcodeTimer=null;barcodeControls?.stop?.();barcodeControls=null;barcodeStream?.getTracks().forEach(track=>track.stop());barcodeStream=null;$('#barcodeVideo').srcObject=null}
function loadBarcodeReader(){if(globalThis.ZXingBrowser)return Promise.resolve(globalThis.ZXingBrowser);return new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/@zxing/browser@0.1.5/umd/zxing-browser.min.js';script.onload=()=>resolve(globalThis.ZXingBrowser);script.onerror=reject;document.head.appendChild(script)})}
function saveBarcodeProduct(code,name){barcodeCache[code]={name,updatedAt:new Date().toISOString()};localStorage.setItem('fridge-barcode-cache',JSON.stringify(barcodeCache))}
function showBarcodeExpiryStep(code,name,cached=false){stopBarcode();pendingBarcode=code;$('#barcodeScanStep').hidden=true;$('#barcodeExpiryStep').hidden=false;$('#barcodeProductName').value=name||'';$('#barcodeExpiryDate').value='';$('#expiryDateCandidates').innerHTML='';$('#barcodeStatus').textContent=cached?'端末に保存された商品情報を使用しました。':code?'商品を確認し、続けて期限表示を読み取ってください。':'入力した食材の期限表示を読み取ってください。';startExpiryCamera()}
function useBarcodeProduct(code,name,cached=false){saveBarcodeProduct(code,name);showBarcodeExpiryStep(code,name,cached)}
async function lookupBarcode(code){const digits=String(code||'').replace(/\D/g,'');$('#manualBarcodeProduct').hidden=true;if(!/^\d{8,14}$/.test(digits)){$('#barcodeStatus').textContent='8〜14桁のバーコード番号を入力してください。';return}$('#barcodeValue').value=digits;if(!/^(45|49)/.test(digits)){$('#barcodeStatus').textContent='海外製品のバーコードは対象外です。日本向けJANコード（45または49から始まる商品）のみ追加できます。';return}if(barcodeCache[digits]?.name){useBarcodeProduct(digits,barcodeCache[digits].name,true);return}$('#barcodeStatus').textContent='国内商品の情報を検索しています…';try{const response=await fetch(`https://jp.openfoodfacts.org/api/v2/product/${digits}.json?fields=product_name,product_name_ja,quantity`);const data=await response.json();const name=data.product?.product_name_ja||data.product?.product_name;if(data.status===1&&name){useBarcodeProduct(digits,name)}else{pendingBarcode=digits;$('#barcodeStatus').textContent=`国内商品データベースに未登録です。JAN ${digits} の商品名を一度入力すると、次回から端末の記録を使います。`;$('#manualBarcodeProduct').hidden=false}}catch{$('#barcodeStatus').textContent='商品検索に接続できませんでした。番号を確認してもう一度お試しください。'}}
async function openBarcode(){const dialog=$('#barcodeDialog');dialog.showModal();$('#barcodeStatus').textContent='カメラを準備しています。';if(!globalThis.isSecureContext||!navigator.mediaDevices?.getUserMedia){$('#barcodeStatus').textContent='カメラを利用できません。JANコードを手入力してください。';return}const video=$('#barcodeVideo');try{if('BarcodeDetector'in globalThis){barcodeStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});video.srcObject=barcodeStream;await video.play();const detector=new BarcodeDetector({formats:['ean_13','ean_8','upc_a','upc_e']});$('#barcodeStatus').textContent='バーコードを枠内に合わせてください。';barcodeTimer=setInterval(async()=>{if(video.readyState<2)return;try{const codes=await detector.detect(video);if(codes[0]){clearInterval(barcodeTimer);await lookupBarcode(codes[0].rawValue)}}catch{}},450)}else{const ZXingBrowser=await loadBarcodeReader();const reader=new ZXingBrowser.BrowserMultiFormatReader();$('#barcodeStatus').textContent='バーコードを枠内に合わせてください。';barcodeControls=await reader.decodeFromVideoDevice(undefined,video,(result)=>{if(result){barcodeControls?.stop();lookupBarcode(result.getText())}})}}catch{$('#barcodeStatus').textContent='自動読取を開始できません。JANコードを手入力してください。'}}
function extractExpiryDates(text){const dates=new Set(),now=new Date(),maxYear=now.getFullYear()+10;for(const match of text.matchAll(/(20\d{2}|\d{2})\s*[年\/\.\-]\s*(\d{1,2})\s*[月\/\.\-]\s*(\d{1,2})\s*日?/g)){let year=Number(match[1]);if(year<100)year+=2000;const month=Number(match[2]),day=Number(match[3]),date=new Date(year,month-1,day);if(date.getFullYear()===year&&date.getMonth()===month-1&&date.getDate()===day&&year<=maxYear)dates.add(iso(date))}return[...dates].sort()}
function stopExpiryCamera(){expiryStream?.getTracks().forEach(track=>track.stop());expiryStream=null;$('#expiryVideo').srcObject=null}
async function startExpiryCamera(){stopExpiryCamera();$('#expiryCameraButton').disabled=true;$('#expiryCameraButton').textContent='カメラを準備中…';$('#expiryOcrStatus').textContent='期限表示へカメラを向けてください。';try{expiryStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});const video=$('#expiryVideo');video.srcObject=expiryStream;await video.play();$('#expiryCameraButton').disabled=false;$('#expiryCameraButton').textContent='期限を読み取る';$('#expiryOcrStatus').textContent='期限表示を枠内に合わせて「期限を読み取る」を押してください。'}catch{$('#expiryCameraButton').textContent='カメラを利用できません';$('#expiryOcrStatus').textContent='カメラを起動できません。下の日付欄へ手入力してください。'}}
function captureExpiryFrame(){const video=$('#expiryVideo'),canvas=$('#expiryCanvas');if(!video.videoWidth){$('#expiryOcrStatus').textContent='カメラの準備ができていません。';return}canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0);$('#expiryCameraButton').disabled=true;canvas.toBlob(blob=>{if(blob)readExpiryImage(blob);else $('#expiryOcrStatus').textContent='映像を取得できませんでした。もう一度お試しください。'},'image/jpeg',.92)}
async function readExpiryImage(blob){const url=URL.createObjectURL(blob);$('#expiryDateCandidates').innerHTML='';$('#expiryOcrStatus').textContent='期限の文字認識を準備しています…';try{const Tesseract=await loadOcr();const result=await Tesseract.recognize(url,'jpn+eng',{logger:progress=>{if(progress.status==='recognizing text')$('#expiryOcrStatus').textContent=`期限を読み取り中… ${Math.round(progress.progress*100)}%`}});const dates=extractExpiryDates(result.data.text);if(dates.length){$('#barcodeExpiryDate').value=dates[0];$('#expiryOcrStatus').textContent=dates.length===1?'日付を読み取りました。正しいか確認してください。':'複数の日付を読み取りました。正しい期限を選んでください。';$('#expiryDateCandidates').innerHTML=dates.map(date=>`<button type="button" class="candidate expiry-date-option" data-date="${date}">${date}</button>`).join('');$$('.expiry-date-option').forEach(button=>button.onclick=()=>{$('#barcodeExpiryDate').value=button.dataset.date;$$('.expiry-date-option').forEach(option=>option.classList.toggle('selected',option===button))})}else $('#expiryOcrStatus').textContent='日付を認識できませんでした。もう一度読み取るか、日付欄へ手入力してください。'}catch{$('#expiryOcrStatus').textContent='期限を読み取れませんでした。もう一度読み取るか、日付欄へ手入力してください。'}finally{stopExpiryCamera();$('#expiryCameraButton').disabled=false;$('#expiryCameraButton').textContent='もう一度読み取る';setTimeout(()=>URL.revokeObjectURL(url),1000)}}
function continueBarcodeProduct(){const name=$('#barcodeProductName').value.trim();if(!name){$('#expiryOcrStatus').textContent='商品名を入力してください。';$('#barcodeProductName').focus();return}if(pendingBarcode)saveBarcodeProduct(pendingBarcode,name);pendingExpiryDate=$('#barcodeExpiryDate').value;pendingExpiryKind=$('#expiryKind').value;stopBarcode();stopExpiryCamera();$('#barcodeDialog').close();if(!pendingBarcode){if(pendingExpiryDate)$('#expiryDate').value=pendingExpiryDate;$('#expiryHint').textContent=`読み取った${pendingExpiryKind||'期限'}です。日付を再確認してください。`;return}$('#itemName').value=name;applyFoodPreset(name);navigate('add');showStep(1);const toast=$('#toast');toast.textContent='商品と期限を確認しました。保存場所を設定してください';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
function cancelBarcodeFlow(){stopBarcode();stopExpiryCamera();pendingBarcode='';pendingExpiryDate='';pendingExpiryKind=''}
$('#barcodeButton').onclick=()=>{$('#barcodeDialogEyebrow').textContent='JAN / EAN';$('#barcodeDialogTitle').textContent='バーコードで追加';$('#manualBarcodeProduct').hidden=true;$('#barcodeScanStep').hidden=false;$('#barcodeExpiryStep').hidden=true;$('#expiryDateCandidates').innerHTML='';openBarcode()};$('#manualExpiryButton').onclick=()=>{const name=$('#itemName').value.trim();if(!name){$('#itemName').reportValidity();return}pendingExpiryDate='';pendingExpiryKind='';const category=ruleFor(name).category;$('#expiryKind').value=['肉類','魚介類'].includes(category)?'消費期限':'賞味期限';$('#barcodeDialogEyebrow').textContent='EXPIRY OCR';$('#barcodeDialogTitle').textContent='期限を読み取る';$('#barcodeDialog').showModal();showBarcodeExpiryStep('',name)};$('#closeBarcode').onclick=()=>{$('#barcodeDialog').close();cancelBarcodeFlow()};$('#barcodeDialog').addEventListener('cancel',cancelBarcodeFlow);$('#lookupBarcode').onclick=()=>lookupBarcode($('#barcodeValue').value);$('#barcodeValue').onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();lookupBarcode(event.target.value)}};$('#manualBarcodeProduct').onclick=()=>showBarcodeExpiryStep(pendingBarcode,'');$('#expiryCameraButton').onclick=()=>expiryStream?captureExpiryFrame():startExpiryCamera();$('#confirmBarcodeProduct').onclick=continueBarcodeProduct;
$('#itemForm').addEventListener('submit',()=>{const expiryKind=pendingExpiryKind;if(pendingBarcode){const name=$('#itemName').value.trim();if(name)saveBarcodeProduct(pendingBarcode,name)}setTimeout(()=>{if(expiryKind&&items[0]){items[0].expiryKind=expiryKind;save()}pendingBarcode='';pendingExpiryDate='';pendingExpiryKind=''},0)},{capture:true});
$('#purchaseDate').value=iso(new Date());$('#today').textContent=new Intl.DateTimeFormat('ja-JP',{dateStyle:'long',weekday:'short'}).format(new Date());$('#filterLocation').innerHTML+=FRIDGE.locations.map(x=>`<option value="${x.id}">${x.name}</option>`).join('');renderQuickPicker();refreshStoredItems();window.addEventListener('pageshow',refreshStoredItems);window.addEventListener('focus',refreshStoredItems);window.addEventListener('storage',event=>{if(event.key==='fridge-items')refreshStoredItems()});
if('serviceWorker' in navigator&&location.protocol.startsWith('http'))window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
