const FRIDGE={model:'MR-JW52TJ',totalLiters:517,locations:[{id:'refrigerator-upper',name:'冷蔵室・上段',capacity:75},{id:'refrigerator-middle',name:'冷蔵室・中段',capacity:75},{id:'refrigerator-lower',name:'冷蔵室・下段',capacity:87},{id:'door',name:'ドアポケット',capacity:40},{id:'vegetable',name:'野菜室',capacity:98},{id:'ice',name:'製氷室',capacity:23},{id:'switch',name:'切替室',capacity:30},{id:'freezer',name:'冷凍室',capacity:89}]};
const RULES=[{words:['牛乳','豆腐'],category:'乳製品・日配',cold:5,frozen:30},{words:['豚','牛肉','鶏','ひき肉','肉'],category:'肉類',cold:3,frozen:30},{words:['魚','鮭','刺身'],category:'魚介類',cold:2,frozen:21},{words:['キャベツ','白菜','にんじん','大根','玉ねぎ','野菜'],category:'野菜',cold:10,frozen:30},{words:['卵'],category:'卵',cold:14,frozen:30},{words:['ヨーグルト'],category:'乳製品',cold:7,frozen:21}];
const FOOD_PRESETS=[{name:'牛乳',aliases:['ぎゅうにゅう','ミルク'],liters:1.1,unit:'本'},{name:'キャベツ',aliases:['きゃべつ','甘藍'],liters:5,unit:'個'},{name:'白菜',aliases:['はくさい'],liters:6,unit:'個'},{name:'玉ねぎ',aliases:['たまねぎ','タマネギ','玉葱'],liters:.6,unit:'個'},{name:'にんじん',aliases:['ニンジン','人参'],liters:.5,unit:'本'},{name:'大根',aliases:['だいこん','ダイコン'],liters:2.5,unit:'本'},{name:'レタス',aliases:['れたす','萵苣'],liters:4,unit:'個'},{name:'トマト',aliases:['とまと','蕃茄'],liters:.5,unit:'個'},{name:'きゅうり',aliases:['キュウリ','胡瓜'],liters:.35,unit:'本'},{name:'じゃがいも',aliases:['ジャガイモ','馬鈴薯','じゃが芋'],liters:.4,unit:'個'},{name:'豚こま肉',aliases:['ぶたこまにく','ブタコマニク','豚肉','ぶたにく','ブタニク'],liters:.8,unit:'パック'},{name:'牛肉',aliases:['ぎゅうにく','ギュウニク'],liters:.8,unit:'パック'},{name:'鶏肉',aliases:['とりにく','トリニク','鳥肉'],liters:1,unit:'パック'},{name:'ひき肉',aliases:['ひきにく','ヒキニク','挽肉','挽き肉'],liters:.7,unit:'パック'},{name:'鮭',aliases:['さけ','サケ','しゃけ','シャケ'],liters:.6,unit:'パック'},{name:'卵',aliases:['たまご','タマゴ','玉子'],liters:2,unit:'パック'},{name:'豆腐',aliases:['とうふ','トウフ'],liters:.5,unit:'パック'},{name:'ヨーグルト',aliases:['よーぐると'],liters:.5,unit:'個'},{name:'チーズ',aliases:['ちーず','乾酪'],liters:.35,unit:'パック'},{name:'納豆',aliases:['なっとう','ナットウ'],liters:.45,unit:'パック'},{name:'ジュース',aliases:['じゅーす','果汁飲料'],liters:1.1,unit:'本'},{name:'冷凍食品',aliases:['れいとうしょくひん','レイトウショクヒン'],liters:1,unit:'袋'}];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let items=JSON.parse(localStorage.getItem('fridge-items')||'[]');let currentStep=1;let activeMapLocations=[];let pendingLocation='';let cameraStream=null;
const iso=d=>{const x=new Date(d);x.setMinutes(x.getMinutes()-x.getTimezoneOffset());return x.toISOString().slice(0,10)};
const addDays=(date,n)=>{const d=new Date(date);d.setDate(d.getDate()+n);return iso(d)};
function normalizeFoodText(value){return String(value||'').normalize('NFKC').toLowerCase().replace(/[ァ-ヶ]/g,char=>String.fromCharCode(char.charCodeAt(0)-0x60)).replace(/[\s・ー]/g,'')}
function ruleFor(name){const normalizedNames=[name,presetFor(name).name].map(normalizeFoodText);return RULES.find(rule=>rule.words.some(word=>normalizedNames.some(value=>value.includes(normalizeFoodText(word)))))||{category:'その他',cold:7,frozen:30}}
function presetFor(name){const normalized=normalizeFoodText(name);return FOOD_PRESETS.find(food=>[food.name,...food.aliases].some(word=>normalized.includes(normalizeFoodText(word))))||{name:'その他',liters:1,unit:'個'}}
function itemLiters(item){return Number(item.volumeLiters??presetFor(item.name).liters)*Number(item.quantity||1)}
function showStep(n){currentStep=n;$$('.form-step').forEach((e,i)=>e.classList.toggle('active',i===n-1));$$('.step').forEach((e,i)=>e.classList.toggle('current',i===n-1));if(n===3){prepareFinalStep();const preferred=$(`input[name="location"][value="${pendingLocation}"]`);if(preferred){preferred.checked=true;preferred.dispatchEvent(new Event('change'))}}}
function prepareFinalStep(){const storage=$('input[name="storage"]:checked').value;const cold=storage==='冷蔵';const rooms=cold?[['refrigerator-upper','上段'],['refrigerator-middle','中段'],['refrigerator-lower','下段'],['door','ドアポケット'],['vegetable','野菜室']]:[['switch','切替室'],['freezer','冷凍室']];const option=(id,label,extra='')=>`<label class="map-location-option ${extra}"><input type="radio" name="location" value="${id}" ${id===rooms[0][0]?'checked':''}><span><b>${label}</b><small>${FRIDGE.locations.find(x=>x.id===id)?.capacity||''}L</small></span></label>`;$('#locationChoices').innerHTML=`<div class="location-map-title"><b>MR-JW52TJ</b><small>${storage}できる場所を表示しています</small></div><div class="location-fridge ${cold?'cold-mode':'frozen-mode'}">${cold?`<div class="open-fridge"><div class="shelf-column">${option('refrigerator-upper','冷蔵室・上段','shelf upper')}${option('refrigerator-middle','冷蔵室・中段','shelf middle')}${option('refrigerator-lower','冷蔵室・下段','shelf lower')}</div>${option('door','ドアポケット','open-door')}</div><div class="closed-pair"><div class="disabled-room">製氷室</div><div class="disabled-room">切替室</div></div><div class="disabled-room wide">冷凍室</div>${option('vegetable','野菜室','wide-room')}`:`<div class="disabled-room tall">冷蔵室</div><div class="closed-pair"><div class="disabled-room">製氷室</div>${option('switch','切替室','compact-room')}</div>${option('freezer','冷凍室','wide-room freezer-choice')}<div class="disabled-room wide">野菜室</div>`}</div><p id="selectedLocation" class="selected-location"></p>`;const update=()=>{const selected=$('input[name="location"]:checked');$('#selectedLocation').textContent=`選択中：${FRIDGE.locations.find(x=>x.id===selected.value)?.name}`};$$('input[name="location"]').forEach(input=>input.onchange=update);update();const rule=ruleFor($('#itemName').value.trim());const days=storage==='冷凍'?rule.frozen:rule.cold;$('#expiryDate').value=addDays($('#purchaseDate').value,days);$('#expiryHint').textContent=`「${rule.category}・${storage}」の一般的な目安として購入日から${days}日後を提案しています。表示や状態を優先して変更してください。`}
function save(){localStorage.setItem('fridge-items',JSON.stringify(items));render()}
function remaining(item){return Math.ceil((new Date(item.expiry+'T23:59:59')-new Date())/86400000)}
function card(item){const days=remaining(item),status=days<0?`${Math.abs(days)}日超過`:days===0?'今日まで':`あと${days}日`;return `<article class="item-card"><div class="item-head"><div><span class="tag">${item.category}</span><h3>${item.name}</h3></div><button class="delete" data-delete="${item.id}" aria-label="削除">削除</button></div><p class="item-meta">${item.quantity}${item.unit} ・ ${item.storage}<br>${FRIDGE.locations.find(x=>x.id===item.location)?.name||item.location}<br>占有目安 ${itemLiters(item).toFixed(1)}L</p><p class="expiry ${days<0?'overdue':days<=3?'soon':''}">${status}（${item.expiry}）</p></article>`}
function roomUsage(locations){return items.filter(item=>locations.includes(item.location)).reduce((sum,item)=>sum+itemLiters(item),0)}
function roomCapacity(locations){return locations.reduce((sum,id)=>sum+(FRIDGE.locations.find(room=>room.id===id)?.capacity||0),0)}
function renderMap(){$$('.map-items').forEach(area=>{const locations=area.dataset.mapItems.split(','),stored=items.filter(item=>locations.includes(item.location)),used=roomUsage(locations),capacity=roomCapacity(locations),percent=Math.min(100,used/capacity*100);area.innerHTML=`<span class="room-capacity">${used.toFixed(1)} / ${capacity}L（残り${Math.max(0,capacity-used).toFixed(1)}L）</span><span class="mini-meter"><i style="width:${percent}%"></i></span>`+(stored.length?stored.slice(0,4).map(item=>`<span class="map-item">${item.name}</span>`).join('')+(stored.length>4?`<span class="map-item">ほか${stored.length-4}件</span>`:''):'<span class="map-empty">空</span>')});$$('.compartment').forEach(room=>{const locations=room.dataset.mapLocation.split(',');room.classList.toggle('selected',activeMapLocations.length>0&&locations.some(id=>activeMapLocations.includes(id)));room.onclick=()=>{activeMapLocations=locations;$('#filterLocation').value=locations.length===1?locations[0]:'';render()}});const action=$('#mapAddAction');action.hidden=!activeMapLocations.length;if(activeMapLocations.length){$('#mapAddPlace').textContent=activeMapLocations.length===1?FRIDGE.locations.find(room=>room.id===activeMapLocations[0])?.name:'冷蔵室（棚は登録時に選択）'}$('#clearLocation').onclick=()=>{activeMapLocations=[];$('#filterLocation').value='';render()}}
function render(){const q=$('#searchInput').value.toLowerCase(),loc=$('#filterLocation').value,locations=activeMapLocations.length?activeMapLocations:(loc?[loc]:[]);const filtered=items.filter(x=>x.name.toLowerCase().includes(q)&&(!locations.length||locations.includes(x.location)));$('#inventoryList').innerHTML=filtered.length?filtered.map(card).join(''):'<div class="empty">この場所には食材がありません。</div>';const place=locations.length===1?FRIDGE.locations.find(x=>x.id===locations[0])?.name:locations.length?'冷蔵室（各段）':'冷蔵庫全体';$('#inventorySummary').textContent=`${place}：${filtered.length}件`;const alerts=items.filter(x=>remaining(x)<=3).sort((a,b)=>remaining(a)-remaining(b));$('#alertList').innerHTML=alerts.length?alerts.map(card).join(''):'<div class="empty">3日以内の期限リマインドはありません。</div>';$('#itemCount').textContent=items.length;$('#alertCount').textContent=alerts.length;const liters=Math.min(FRIDGE.totalLiters,items.reduce((n,x)=>n+itemLiters(x),0));$('#capacityText').textContent=`${liters.toFixed(1)} / ${FRIDGE.totalLiters} L`;$('#capacityBar').style.width=`${liters/FRIDGE.totalLiters*100}%`;renderMap()}
function navigate(view){$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$$('.view').forEach(x=>x.classList.remove('active'));$(`#${view}View`).classList.add('active');$('#pageTitle').textContent={add:'何を追加しますか？',inventory:'冷蔵庫の中身',alerts:'期限リマインド'}[view];render()}
$$('.next').forEach(b=>b.onclick=()=>{if(currentStep===1&&!$('#itemName').value.trim()){ $('#itemName').reportValidity();return}showStep(currentStep+1)});$$('.back').forEach(b=>b.onclick=()=>showStep(currentStep-1));$$('.nav').forEach(b=>b.onclick=()=>navigate(b.dataset.view));
$('#itemForm').onsubmit=e=>{e.preventDefault();const name=$('#itemName').value.trim(),rule=ruleFor(name);items.unshift({id:globalThis.crypto?.randomUUID?.()||`item-${Date.now()}-${Math.random().toString(16).slice(2)}`,name,category:rule.category,quantity:$('#quantity').value,unit:$('#unit').value,volumeLiters:Number($('#volume').value),storage:$('input[name="storage"]:checked').value,location:$('input[name="location"]:checked').value,purchased:$('#purchaseDate').value,expiry:$('#expiryDate').value,createdAt:new Date().toISOString()});pendingLocation='';save();e.target.reset();$('#quantity').value=1;$('#volume').value=1;$('#purchaseDate').value=iso(new Date());showStep(1);const t=$('#toast');t.textContent=`${name}を追加しました`;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200);navigate('inventory')};
document.addEventListener('click',e=>{const id=e.target.dataset.delete;if(id&&confirm('この食材を削除しますか？')){items=items.filter(x=>x.id!==id);save()}});$('#searchInput').oninput=render;$('#filterLocation').onchange=()=>{activeMapLocations=$('#filterLocation').value?[$('#filterLocation').value]:[];render()};
$('#addToSelectedRoom').onclick=()=>{pendingLocation=activeMapLocations.length===1?activeMapLocations[0]:'';const frozen=['freezer','switch'].includes(pendingLocation);$(`input[name="storage"][value="${frozen?'冷凍':'冷蔵'}"]`).checked=true;showStep(1);navigate('add');setTimeout(()=>$('#itemName').focus(),0)};
function applyFoodPreset(name){const food=presetFor(name);$('#volume').value=food.liters;$('#unit').value=[...$('#unit').options].some(option=>option.value===food.unit)?food.unit:$('#unit').value;$('#volumeHint').textContent=`${food.name}の一般的な包装・形状を含む占有目安：1${food.unit}あたり約${food.liters}L。実物に合わせて修正できます。`}
function recognizeImage(file){const filename=normalizeFoodText(file.name);const matches=FOOD_PRESETS.filter(food=>[food.name,...food.aliases].some(word=>filename.includes(normalizeFoodText(word))));return matches.length?matches:FOOD_PRESETS.slice(0,8)}
function foodMatches(text){const normalized=normalizeFoodText(text);return FOOD_PRESETS.filter(food=>[food.name,...food.aliases].some(word=>normalized.includes(normalizeFoodText(word))))}
function renderImageCandidates(candidates,message){$('#imageStatus').textContent=message;$('#imageCandidates').innerHTML=candidates.map(food=>`<button type="button" class="candidate" data-food-name="${food.name}">${food.name}</button>`).join('');$$('.candidate').forEach(button=>button.onclick=()=>{$('#itemName').value=button.dataset.foodName;applyFoodPreset(button.dataset.foodName);$('#imageStatus').textContent=`「${button.dataset.foodName}」を入力しました。必要なら修正してください。`})}
function loadOcr(){if(globalThis.Tesseract)return Promise.resolve(globalThis.Tesseract);return new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';script.onload=()=>resolve(globalThis.Tesseract);script.onerror=reject;document.head.appendChild(script)})}
async function showImageCandidates(file){const assistant=$('#imageAssistant'),preview=$('#imagePreview'),url=URL.createObjectURL(file);assistant.hidden=false;preview.src=url;const filenameMatches=recognizeImage(file);renderImageCandidates(filenameMatches,'画像を確認しています。レシートの場合は文字の読み取りに少し時間がかかります。');try{const Tesseract=await loadOcr();const result=await Tesseract.recognize(url,'jpn+eng',{logger:progress=>{if(progress.status==='recognizing text')$('#imageStatus').textContent=`レシートを読み取り中… ${Math.round(progress.progress*100)}%`}});const matches=foodMatches(result.data.text);renderImageCandidates(matches.length?matches:filenameMatches,matches.length?`レシートから${matches.length}件の食材候補を見つけました。`:'文字は読み取れましたが、登録済み食材名との一致がありません。候補を選ぶか手入力してください。')}catch{renderImageCandidates(filenameMatches,'文字認識を利用できませんでした。候補を選ぶか手入力してください。')}finally{setTimeout(()=>URL.revokeObjectURL(url),1000)}}
function stopCamera(){cameraStream?.getTracks().forEach(track=>track.stop());cameraStream=null;$('#cameraVideo').srcObject=null}
async function openCamera(){const dialog=$('#cameraDialog');dialog.showModal();$('#takePhoto').disabled=true;$('#cameraStatus').textContent='カメラを準備しています。';if(!globalThis.isSecureContext||!navigator.mediaDevices?.getUserMedia){$('#cameraStatus').textContent='この環境ではカメラを直接起動できません。HTTPSで開くか、画像を選んでください。';return}try{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});$('#cameraVideo').srcObject=cameraStream;await $('#cameraVideo').play();$('#takePhoto').disabled=false;$('#cameraStatus').textContent='食材またはレシート全体が枠内に入るようにしてください。'}catch(error){$('#cameraStatus').textContent=error.name==='NotAllowedError'?'カメラが許可されませんでした。ブラウザの設定から許可するか、画像を選んでください。':'カメラを起動できませんでした。画像選択を利用してください。'}}
function capturePhoto(){const video=$('#cameraVideo'),canvas=$('#cameraCanvas');if(!video.videoWidth)return;canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0);canvas.toBlob(blob=>{if(!blob)return;const file=new File([blob],`camera-${Date.now()}.jpg`,{type:'image/jpeg'});stopCamera();$('#cameraDialog').close();showImageCandidates(file)},'image/jpeg',.9)}
$('#receiptButton').onclick=openCamera;$('#closeCamera').onclick=()=>{$('#cameraDialog').close();stopCamera()};$('#cameraDialog').addEventListener('cancel',stopCamera);$('#takePhoto').onclick=capturePhoto;$('#fallbackImage').onclick=()=>$('#imageInput').click();$('#chooseAnotherImage').onclick=openCamera;$('#imageInput').onchange=()=>{const file=$('#imageInput').files[0];if(file){stopCamera();if($('#cameraDialog').open)$('#cameraDialog').close();showImageCandidates(file)}};$('#itemName').oninput=()=>applyFoodPreset($('#itemName').value);$('#foodSuggestions').innerHTML=FOOD_PRESETS.map(food=>`<option value="${food.name}"></option>`).join('');
$('#purchaseDate').value=iso(new Date());$('#today').textContent=new Intl.DateTimeFormat('ja-JP',{dateStyle:'long',weekday:'short'}).format(new Date());$('#filterLocation').innerHTML+=FRIDGE.locations.map(x=>`<option value="${x.id}">${x.name}</option>`).join('');render();
if('serviceWorker' in navigator&&location.protocol.startsWith('http'))window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
