const DEFAULT_FRIDGE={model:'初期レイアウト',locations:[{id:'refrigerator-upper',name:'冷蔵室・上段',capacity:75,storage:'冷蔵'},{id:'refrigerator-middle',name:'冷蔵室・中段',capacity:75,storage:'冷蔵'},{id:'refrigerator-lower',name:'冷蔵室・下段',capacity:87,storage:'冷蔵'},{id:'door',name:'ドアポケット',capacity:40,storage:'冷蔵'},{id:'vegetable',name:'野菜室',capacity:98,storage:'冷蔵'},{id:'ice',name:'製氷室',capacity:23,storage:'冷凍'},{id:'switch',name:'切替室',capacity:30,storage:'冷凍'},{id:'freezer',name:'冷凍室',capacity:89,storage:'冷凍'}]};
const savedFridge=JSON.parse(localStorage.getItem('fridge-profile')||'null');let FRIDGE=savedFridge?.locations?.length?savedFridge:JSON.parse(JSON.stringify(DEFAULT_FRIDGE));FRIDGE.totalLiters=FRIDGE.locations.reduce((sum,room)=>sum+Number(room.capacity),0);
const DEFAULT_RULES=[{words:['牛乳','豆腐'],category:'乳製品・日配',cold:5,frozen:30},{words:['ウインナー','ソーセージ'],category:'肉類',cold:14,frozen:60},{words:['ベーコン'],category:'肉類',cold:7,frozen:30},{words:['豚','牛肉','鶏','ひき肉','肉'],category:'肉類',cold:3,frozen:30},{words:['魚','鮭','刺身'],category:'魚介類',cold:2,frozen:21},{words:['もやし'],category:'野菜',cold:3,frozen:14},{words:['キャベツ','白菜','にんじん','大根','玉ねぎ','野菜'],category:'野菜',cold:10,frozen:30},{words:['卵'],category:'卵',cold:14,frozen:30},{words:['ヨーグルト'],category:'乳製品',cold:7,frozen:21},{words:['しょうゆ','味噌','マヨネーズ','ケチャップ','ソース','ドレッシング','めんつゆ','ポン酢','みりん','料理酒','酢','わさび','からし'],category:'調味料',cold:60,frozen:90}];
let RULES=[...Object.values(JSON.parse(localStorage.getItem('fridge-food-rules')||'{}')),...DEFAULT_RULES];
const FOOD_PRESETS=[{name:'牛乳',aliases:['ぎゅうにゅう','ミルク'],liters:1.1,unit:'本'},{name:'キャベツ',aliases:['きゃべつ','甘藍'],liters:5,unit:'個'},{name:'白菜',aliases:['はくさい'],liters:6,unit:'個'},{name:'玉ねぎ',aliases:['たまねぎ','タマネギ','玉葱'],liters:.6,unit:'個'},{name:'にんじん',aliases:['ニンジン','人参'],liters:.5,unit:'本'},{name:'大根',aliases:['だいこん','ダイコン'],liters:2.5,unit:'本'},{name:'レタス',aliases:['れたす','萵苣'],liters:4,unit:'個'},{name:'トマト',aliases:['とまと','蕃茄'],liters:.5,unit:'個'},{name:'きゅうり',aliases:['キュウリ','胡瓜'],liters:.35,unit:'本'},{name:'じゃがいも',aliases:['ジャガイモ','馬鈴薯','じゃが芋'],liters:.4,unit:'個'},{name:'豚こま肉',aliases:['ぶたこまにく','ブタコマニク','豚肉','ぶたにく','ブタニク'],liters:.8,unit:'パック'},{name:'牛肉',aliases:['ぎゅうにく','ギュウニク'],liters:.8,unit:'パック'},{name:'鶏肉',aliases:['とりにく','トリニク','鳥肉'],liters:1,unit:'パック'},{name:'ひき肉',aliases:['ひきにく','ヒキニク','挽肉','挽き肉'],liters:.7,unit:'パック'},{name:'鮭',aliases:['さけ','サケ','しゃけ','シャケ'],liters:.6,unit:'パック'},{name:'卵',aliases:['たまご','タマゴ','玉子'],liters:2,unit:'パック'},{name:'豆腐',aliases:['とうふ','トウフ'],liters:.5,unit:'パック'},{name:'ヨーグルト',aliases:['よーぐると'],liters:.5,unit:'個'},{name:'チーズ',aliases:['ちーず','乾酪'],liters:.35,unit:'パック'},{name:'納豆',aliases:['なっとう','ナットウ'],liters:.45,unit:'パック'},{name:'ジュース',aliases:['じゅーす','果汁飲料'],liters:1.1,unit:'本'},{name:'冷凍食品',aliases:['れいとうしょくひん','レイトウショクヒン'],liters:1,unit:'袋'}];
const CONDIMENT_PRESETS=[{name:'しょうゆ',aliases:['ショウユ','醤油'],liters:.7,unit:'本'},{name:'味噌',aliases:['みそ','ミソ'],liters:.8,unit:'個'},{name:'マヨネーズ',aliases:['まよねーず','マヨ'],liters:.5,unit:'本'},{name:'ケチャップ',aliases:['けちゃっぷ','トマトケチャップ'],liters:.5,unit:'本'},{name:'ソース',aliases:['そーす','ウスターソース','中濃ソース','とんかつソース'],liters:.6,unit:'本'},{name:'ドレッシング',aliases:['どれっしんぐ'],liters:.5,unit:'本'},{name:'めんつゆ',aliases:['メンツユ','麺つゆ','麺汁'],liters:.6,unit:'本'},{name:'ポン酢',aliases:['ぽんず','ポンズ','ぽん酢'],liters:.5,unit:'本'},{name:'みりん',aliases:['ミリン','味醂'],liters:1,unit:'本'},{name:'料理酒',aliases:['りょうりしゅ','リョウリシュ'],liters:1,unit:'本'},{name:'酢',aliases:['す','ス','食酢'],liters:.6,unit:'本'},{name:'わさび',aliases:['ワサビ','山葵'],liters:.15,unit:'本'},{name:'からし',aliases:['カラシ','辛子','芥子'],liters:.15,unit:'本'}];FOOD_PRESETS.push(...CONDIMENT_PRESETS);
const EXTRA_FOOD_PRESETS=[{name:'さば',aliases:['サバ','鯖'],liters:.7,unit:'パック'},{name:'まぐろ',aliases:['マグロ','鮪'],liters:.6,unit:'パック'},{name:'ぶり',aliases:['ブリ','鰤'],liters:.7,unit:'パック'},{name:'あじ',aliases:['アジ','鯵'],liters:.6,unit:'パック'},{name:'りんご',aliases:['リンゴ','林檎'],liters:.5,unit:'個'},{name:'バナナ',aliases:['ばなな','甘蕉'],liters:1,unit:'袋'},{name:'みかん',aliases:['ミカン','蜜柑'],liters:.35,unit:'個'}];FOOD_PRESETS.push(...EXTRA_FOOD_PRESETS);RULES.push({words:['りんご','バナナ','みかん','果物'],category:'果物',cold:10,frozen:30});
const QUICK_CATEGORIES=[{id:'meat',name:'肉',mark:'肉類',foods:['豚こま肉','牛肉','鶏肉','ひき肉','ウインナー','ベーコン']},{id:'fish',name:'魚',mark:'魚介',foods:['鮭','さば','まぐろ','ぶり','あじ']},{id:'vegetable',name:'野菜',mark:'野菜',foods:['キャベツ','白菜','玉ねぎ','にんじん','大根','レタス','トマト','きゅうり','じゃがいも','もやし']},{id:'fruit',name:'果物',mark:'果物',foods:['りんご','バナナ','みかん']},{id:'dairy',name:'乳製品',mark:'乳製品',foods:['牛乳','ヨーグルト','チーズ']},{id:'daily',name:'卵・日配',mark:'卵日配',foods:['卵','豆腐','納豆']},{id:'seasoning',name:'調味料',mark:'調味料',foods:['しょうゆ','味噌','マヨネーズ','ケチャップ','ソース','ドレッシング','めんつゆ','ポン酢']},{id:'frozen',name:'冷凍食品',mark:'冷凍品',foods:['冷凍食品']},{id:'other',name:'その他',mark:'その他',foods:[]}];
const {iso,addDays,normalizeFoodText,readStoredItems,readStoredObject,remaining,freshnessFor,escapeHtml}=globalThis.FridgeUtils;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let pendingDraft=null;let undoSnapshot=null;let items=readStoredItems();let barcodeCache=readStoredObject('fridge-barcode-cache');let customCategoryFoods=readStoredObject('fridge-custom-foods');let activeQuickCategory='';let deletingCustomFood=false;let currentStep=1;let activeMapLocations=[];let pendingLocation='';let pendingBarcode='';let pendingExpiryDate='';let pendingExpiryKind='';let barcodeStream=null;let expiryStream=null;let barcodeTimer=null;let barcodeControls=null;
const cloudConfig=globalThis.FRIDGE_CLOUD_CONFIG||{};const cloudConfigured=/^https:\/\/.+\.supabase\.co$/.test(cloudConfig.supabaseUrl||'')&&Boolean(cloudConfig.supabaseAnonKey);let cloudClient=null;let currentCloudUser=null;let cloudSaveTimer=null;let applyingCloudData=false;
let editingItemId='';
function ruleFor(name){const normalizedNames=[name,presetFor(name).name].map(normalizeFoodText);return RULES.find(rule=>rule.words.some(word=>normalizedNames.some(value=>value.includes(normalizeFoodText(word)))))||{category:'その他',cold:7,frozen:30}}
function presetFor(name){const normalized=normalizeFoodText(name);return FOOD_PRESETS.find(food=>[food.name,...food.aliases].some(word=>normalized.includes(normalizeFoodText(word))))||{name:'その他',liters:1,unit:'個'}}
function itemLiters(item){return Number(item.volumeLiters??presetFor(item.name).liters)*Number(item.quantity||1)}
function showStep(n){currentStep=n;$$('.form-step').forEach((e,i)=>e.classList.toggle('active',i===n-1));$$('.step').forEach((e,i)=>e.classList.toggle('current',i===n-1));if(n===3){prepareFinalStep();const preferred=$(`input[name="location"][value="${pendingLocation}"]`);if(preferred){preferred.checked=true;preferred.dispatchEvent(new Event('change'))}if(pendingExpiryDate){$('#expiryDate').value=pendingExpiryDate;$('#expiryHint').textContent=`バーコード入力で確認した${pendingExpiryKind||'期限'}です。日付を再確認してください。`}}}
function prepareFinalStep(){const storage=$('input[name="storage"]:checked').value,available=FRIDGE.locations.filter(room=>room.storage===storage);const option=room=>{const enabled=room.storage===storage;return`<label class="map-location-option whole-room room-${room.id} ${enabled?'':'unavailable'}"><input type="radio" name="location" value="${room.id}" ${room===available[0]?'checked':''} ${enabled?'':'disabled'}><span><b>${room.name}</b><small>${room.capacity}L${enabled?'':`・${room.storage}`}</small></span></label>`};$('#locationChoices').innerHTML=`<div class="location-map-title"><b>冷蔵庫全体</b><small>色の付いた${storage}区画を選択</small></div><div class="whole-fridge-choice">${FRIDGE.locations.map(option).join('')}</div><p id="selectedLocation" class="selected-location"></p>`;const update=()=>{const selected=$('input[name="location"]:checked'),room=FRIDGE.locations.find(x=>x.id===selected?.value);$('#selectedLocation').textContent=room?`選択中：${room.name}`:'この保存状態の区画を設定画面で追加してください'};$$('input[name="location"]').forEach(input=>input.onchange=update);update();const rule=ruleFor($('#itemName').value.trim()),days=storage==='冷凍'?rule.frozen:rule.cold;$('#expiryDate').value=addDays($('#purchaseDate').value,days);$('#expiryHint').textContent=`「${rule.category}・${storage}」の目安として購入日から${days}日後を提案しています。`}
function storeLocalState(){localStorage.setItem('fridge-items',JSON.stringify(items));localStorage.setItem('fridge-custom-foods',JSON.stringify(customCategoryFoods));localStorage.setItem('fridge-barcode-cache',JSON.stringify(barcodeCache))}
async function persistCloudState(){if(!cloudClient||!currentCloudUser||applyingCloudData)return;const{error}=await cloudClient.from('fridge_user_data').upsert({user_id:currentCloudUser.id,items,custom_foods:customCategoryFoods,barcode_cache:barcodeCache,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error){$('#cloudModeBadge').textContent='同期エラー';console.error(error)}else $('#cloudModeBadge').textContent='同期済み'}
function queueCloudSave(){if(!cloudClient||!currentCloudUser||applyingCloudData)return;clearTimeout(cloudSaveTimer);$('#cloudModeBadge').textContent='同期中';cloudSaveTimer=setTimeout(persistCloudState,350)}
function save(){storeLocalState();render();renderQuickPicker();queueCloudSave()}
function refreshStoredItems(){items=readStoredItems(items);$('#itemCount').textContent=items.length;render()}
function card(item){const days=remaining(item),freshness=freshnessFor(days),place=FRIDGE.locations.find(x=>x.id===item.location)?.name||item.location,kind=item.expiryKind||'保存目安',state=item.openState||'未開封';return `<article class="item-card compact-item-card freshness-${freshness.tone}"><div class="item-compact-line item-compact-main"><div class="item-identity"><span class="tag">${escapeHtml(item.category)}</span><strong>${escapeHtml(item.name)}</strong><span>${item.quantity}${escapeHtml(item.unit)}・${item.storage}</span></div><div class="item-card-actions"><button class="edit" data-edit="${item.id}" aria-label="編集">編集</button><button class="delete" data-delete="${item.id}" aria-label="削除">削除</button></div></div><div class="item-compact-line item-compact-sub"><span>${escapeHtml(place)}・${state}</span><span class="freshness-label"><b>${freshness.label}</b>・${freshness.status}</span></div><small class="expiry-kind-label">${kind} ${item.expiry}</small></article>`}
function todayCard(item){const days=remaining(item),freshness=freshnessFor(days);return`<article class="today-card freshness-${freshness.tone}"><div class="today-card-main"><div><span class="today-status"><b>${freshness.label}</b>・${freshness.status}</span><h3>${escapeHtml(item.name)}</h3><p>${item.quantity}${escapeHtml(item.unit)}・${item.openState||'未開封'}・${item.expiryKind||'保存目安'}</p></div><b>${item.expiry}</b></div><div class="consume-actions"><button data-consume="one" data-item-id="${item.id}">1つ使った</button><button data-consume="half" data-item-id="${item.id}">半分使った</button><button data-consume="all" data-item-id="${item.id}">全部使った</button>${item.storage==='冷蔵'?`<button data-consume="freeze" data-item-id="${item.id}">冷凍した</button>`:''}</div></article>`}
function roomUsage(locations){return items.filter(item=>locations.includes(item.location)).reduce((sum,item)=>sum+itemLiters(item),0)}
function roomCapacity(locations){return locations.reduce((sum,id)=>sum+(FRIDGE.locations.find(room=>room.id===id)?.capacity||0),0)}
function renderMap(){const map=$('#fridgeMap');map.className='fridge-map whole-fridge-choice fridge-map-unified';map.innerHTML=FRIDGE.locations.map(room=>{const stored=items.filter(item=>item.location===room.id),used=roomUsage([room.id]),percent=Math.min(100,used/room.capacity*100);return`<button class="compartment whole-room room-${room.id} ${activeMapLocations.includes(room.id)?'selected':''}" data-map-location="${room.id}"><b>${room.name}</b><small>${used.toFixed(1)} / ${room.capacity}L</small><span class="mini-meter"><i style="width:${percent}%"></i></span><span class="map-items">${stored.slice(0,3).map(item=>`<span class="map-item">${item.name}</span>`).join('')||'<span class="map-empty">空</span>'}</span></button>`}).join('');$$('.compartment').forEach(room=>room.onclick=()=>{activeMapLocations=[room.dataset.mapLocation];$('#filterLocation').value=room.dataset.mapLocation;render()});const action=$('#mapAddAction');action.hidden=!activeMapLocations.length;if(activeMapLocations.length)$('#mapAddPlace').textContent=FRIDGE.locations.find(room=>room.id===activeMapLocations[0])?.name||'';$('#clearLocation').onclick=()=>{activeMapLocations=[];$('#filterLocation').value='';render()}}
function render(){const q=$('#searchInput').value.toLowerCase(),loc=$('#filterLocation').value,locations=activeMapLocations.length?activeMapLocations:(loc?[loc]:[]);const filtered=items.filter(x=>x.name.toLowerCase().includes(q)&&(!locations.length||locations.includes(x.location)));$('#inventoryList').innerHTML=filtered.length?filtered.map(card).join(''):'<div class="empty">この場所には食材がありません。</div>';const place=locations.length===1?FRIDGE.locations.find(x=>x.id===locations[0])?.name:locations.length?'冷蔵室（各段）':'冷蔵庫全体';$('#inventorySummary').textContent=`${place}：${filtered.length}件`;const alerts=items.filter(x=>remaining(x)<=3).sort((a,b)=>remaining(a)-remaining(b)),todayItems=items.filter(x=>remaining(x)<=3).sort((a,b)=>remaining(a)-remaining(b));$('#alertList').innerHTML=alerts.length?alerts.map(card).join(''):'<div class="empty">3日以内の期限リマインドはありません。</div>';$('#todayList').innerHTML=todayItems.length?todayItems.map(todayCard).join(''):'<div class="empty">今すぐ使う食材はありません。</div>';$('#itemCount').textContent=items.length;$('#alertCount').textContent=alerts.length;$('#todayCount').textContent=todayItems.length;const liters=Math.min(FRIDGE.totalLiters,items.reduce((n,x)=>n+itemLiters(x),0));$('#capacityText').textContent=`${liters.toFixed(1)} / ${FRIDGE.totalLiters} L`;$('#capacityBar').style.width=`${liters/FRIDGE.totalLiters*100}%`;renderMap()}
function navigate(view){$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$$('.view').forEach(x=>x.classList.remove('active'));$(`#${view}View`).classList.add('active');$('#pageTitle').textContent={today:'今日使う',add:'何を追加しますか？',inventory:'冷蔵庫の中身',alerts:'期限リマインド',foodSettings:'食材と期限の設定',fridgeSettings:'冷蔵庫の設定'}[view];if(view==='foodSettings')renderFoodSettings();if(view==='fridgeSettings')renderFridgeSettings();render()}
$$('.next').forEach(b=>b.onclick=()=>{if(currentStep===1&&!$('#itemName').value.trim()){ $('#itemName').reportValidity();return}showStep(currentStep+1)});$$('.back').forEach(b=>b.onclick=()=>showStep(currentStep-1));$$('.nav').forEach(b=>b.onclick=()=>navigate(b.dataset.view));
function buildItemDraft(){const name=$('#itemName').value.trim(),rule=ruleFor(name),kind=pendingExpiryKind||$('#itemExpiryKind').value;return{id:globalThis.crypto?.randomUUID?.()||`item-${Date.now()}-${Math.random().toString(16).slice(2)}`,name,category:rule.category,quantity:$('#quantity').value,unit:$('#unit').value,volumeLiters:Number($('#volume').value),storage:$('input[name="storage"]:checked').value,location:$('input[name="location"]:checked').value,purchased:$('#purchaseDate').value,expiry:$('#expiryDate').value,expiryKind:kind,expirySource:kind==='保存目安'?'アプリ推定':'商品表示',openState:$('#openState').value,openedAt:$('#openState').value==='開封済み'?iso(new Date()):'',createdAt:new Date().toISOString()}}
function showItemConfirmation(draft){const room=FRIDGE.locations.find(entry=>entry.id===draft.location);$('#confirmItemName').textContent=draft.name;$('#confirmItemQuantity').textContent=`${draft.quantity}${draft.unit}`;$('#confirmItemLocation').textContent=room?.name||draft.location;$('#confirmItemExpiry').textContent=`${draft.expiryKind} ${draft.expiry}`;$('#confirmItemState').textContent=draft.openState;$('#confirmItemStorage').textContent=draft.storage;$('#confirmItemPurchased').textContent=draft.purchased;$('#confirmItemSource').textContent=draft.expirySource;$('#confirmItemDialog').showModal()}
$('#itemForm').onsubmit=e=>{e.preventDefault();pendingDraft=buildItemDraft();showItemConfirmation(pendingDraft)};
function returnToItemForm(){$('#confirmItemDialog').close();navigate('add');showStep(3);setTimeout(()=>$('#expiryDate').focus(),0)}
$('#changeConfirmedItem').onclick=returnToItemForm;$('#closeConfirmItem').onclick=returnToItemForm;$('#confirmItemDialog').addEventListener('cancel',event=>{event.preventDefault();returnToItemForm()});
$('#saveConfirmedItem').onclick=()=>{if(!pendingDraft)return;if(pendingBarcode)saveBarcodeProduct(pendingBarcode,pendingDraft.name);items.unshift(pendingDraft);const name=pendingDraft.name;pendingDraft=null;pendingLocation='';pendingBarcode='';pendingExpiryDate='';pendingExpiryKind='';save();$('#confirmItemDialog').close();$('#itemForm').reset();$('#quantity').value=1;$('#volume').value=1;$('#purchaseDate').value=iso(new Date());showStep(1);const t=$('#toast');t.textContent=`${name}を追加しました`;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200);navigate('inventory')};
function editLocationOptions(storage,selected){return FRIDGE.locations.filter(room=>room.storage===storage).map(room=>`<option value="${room.id}" ${room.id===selected?'selected':''}>${room.name}</option>`).join('')}
function openItemEditor(id){const item=items.find(entry=>entry.id===id);if(!item)return;editingItemId=id;$('#editItemName').value=item.name;$('#editQuantity').value=item.quantity;$('#editUnit').value=item.unit;$('#editStorage').value=item.storage;$('#editOpenState').value=item.openState||'未開封';$('#editExpiryKind').value=item.expiryKind||'保存目安';$('#editLocation').innerHTML=editLocationOptions(item.storage,item.location);$('#editExpiry').value=item.expiry;$('#editItemDialog').showModal()}
function showUndo(message){$('#undoMessage').textContent=message;$('#undoBar').hidden=false;clearTimeout(showUndo.timer);showUndo.timer=setTimeout(()=>{$('#undoBar').hidden=true;undoSnapshot=null},7000)}
function consumeItem(id,action){const index=items.findIndex(item=>item.id===id);if(index<0)return;undoSnapshot=JSON.parse(JSON.stringify(items));const item=items[index],quantity=Number(item.quantity)||1;if(action==='all'||(action==='one'&&quantity<=1))items.splice(index,1);else if(action==='half')item.quantity=Math.max(.1,Math.round(quantity*5)/10);else if(action==='one')item.quantity=Math.max(.1,Math.round((quantity-1)*10)/10);else if(action==='freeze'){item.storage='冷凍';item.location=FRIDGE.locations.find(room=>room.storage==='冷凍')?.id||item.location;item.expiry=addDays(iso(new Date()),ruleFor(item.name).frozen);item.expiryKind='保存目安';item.expirySource='アプリ推定'}save();showUndo(action==='freeze'?`${item.name}を冷凍へ移しました`:`${item.name}の在庫を更新しました`)}
$('#undoAction').onclick=()=>{if(!undoSnapshot)return;items=undoSnapshot;undoSnapshot=null;$('#undoBar').hidden=true;save()};document.addEventListener('click',e=>{const consume=e.target.dataset.consume,itemId=e.target.dataset.itemId;if(consume&&itemId){consumeItem(itemId,consume);return}const editId=e.target.dataset.edit;if(editId){openItemEditor(editId);return}const id=e.target.dataset.delete;if(id&&confirm('この食材を削除しますか？')){items=items.filter(x=>x.id!==id);save()}});$('#searchInput').oninput=render;$('#filterLocation').onchange=()=>{activeMapLocations=$('#filterLocation').value?[$('#filterLocation').value]:[];render()};
$('#editStorage').onchange=()=>{$('#editLocation').innerHTML=editLocationOptions($('#editStorage').value,'')};$('#closeEditItem').onclick=$('#cancelEditItem').onclick=()=>$('#editItemDialog').close();$('#editItemForm').onsubmit=event=>{event.preventDefault();const index=items.findIndex(item=>item.id===editingItemId);if(index<0)return;const name=$('#editItemName').value.trim(),preset=presetFor(name),rule=ruleFor(name),wasOpen=items[index].openState==='開封済み';items[index]={...items[index],name,category:rule.category,quantity:$('#editQuantity').value,unit:$('#editUnit').value,volumeLiters:preset.liters,storage:$('#editStorage').value,location:$('#editLocation').value,expiry:$('#editExpiry').value,expiryKind:$('#editExpiryKind').value,expirySource:$('#editExpiryKind').value==='保存目安'?'アプリ推定':'商品表示',openState:$('#editOpenState').value,openedAt:$('#editOpenState').value==='開封済み'?(wasOpen?items[index].openedAt:iso(new Date())):''};save();$('#editItemDialog').close();const toast=$('#toast');toast.textContent=`${name}の内容を更新しました`;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)};
$('#addToSelectedRoom').onclick=()=>{pendingLocation=activeMapLocations.length===1?activeMapLocations[0]:'';const frozen=['freezer','switch'].includes(pendingLocation);$(`input[name="storage"][value="${frozen?'冷凍':'冷蔵'}"]`).checked=true;showStep(1);navigate('add');setTimeout(()=>$('#itemName').focus(),0)};
function applyFoodPreset(name){const food=presetFor(name);$('#volume').value=food.liters;$('#unit').value=[...$('#unit').options].some(option=>option.value===food.unit)?food.unit:$('#unit').value}
function foodIconButton(name){const safe=escapeHtml(name);return`<button type="button" class="food-icon-button" data-quick-food="${safe}"><span class="food-pictogram" aria-hidden="true">${escapeHtml(name.slice(0,3))}</span><b>${safe}</b></button>`}
function deleteChoiceButton(name){const safe=escapeHtml(name);return`<button type="button" class="food-icon-button delete-choice" data-remove-choice="${safe}"><span class="food-pictogram" aria-hidden="true">${escapeHtml(name.slice(0,3))}</span><b>${safe}</b></button>`}
function selectQuickFood(name){$('#itemName').value=name;applyFoodPreset(name);showStep(1);$('#itemForm').scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>$('#quantity').focus(),350)}
function foodsForCategory(category){return[...category.foods,...(customCategoryFoods[category.id]||[])]}
function openQuickCategory(id){const category=QUICK_CATEGORIES.find(item=>item.id===id);if(!category)return;activeQuickCategory=id;deletingCustomFood=false;$$('[data-quick-category]').forEach(button=>button.classList.toggle('selected',button.dataset.quickCategory===id));$('#selectedCategoryName').textContent=`${category.name}から選ぶ`;$('#categoryFoods').innerHTML=foodsForCategory(category).map(foodIconButton).join('');$('#customFoodName').placeholder=`${category.name}の食材名`;$('#customFoodForm').hidden=false;$('#manageCustomFoods').textContent='削除';const panel=$('#categoryFoodsPanel');panel.hidden=false;requestAnimationFrame(()=>panel.scrollIntoView({behavior:'smooth',block:'nearest'}))}
function showCustomFoodDeleteMode(){const foods=customCategoryFoods[activeQuickCategory]||[];if(!foods.length){const toast=$('#toast');toast.textContent='削除できる追加食材はありません';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200);return}deletingCustomFood=true;$('#selectedCategoryName').textContent='削除する食材を選択';$('#categoryFoods').innerHTML=foods.map(deleteChoiceButton).join('');$('#customFoodForm').hidden=true;$('#manageCustomFoods').textContent='キャンセル'}
function renderQuickPicker(){$('#categoryGrid').innerHTML=QUICK_CATEGORIES.map(category=>`<button type="button" class="category-icon-button" data-quick-category="${category.id}"><span class="category-pictogram category-${category.id}" aria-hidden="true">${category.mark}</span><b>${category.name}</b></button>`).join('')}
$('#categoryGrid').onclick=event=>{const button=event.target.closest('[data-quick-category]');if(button)openQuickCategory(button.dataset.quickCategory)};$('#categoryFoods').onclick=event=>{const removeChoice=event.target.closest('[data-remove-choice]');if(removeChoice){const name=removeChoice.dataset.removeChoice;if(!confirm(`「${name}」を削除しますか？`))return;customCategoryFoods[activeQuickCategory]=(customCategoryFoods[activeQuickCategory]||[]).filter(food=>food!==name);localStorage.setItem('fridge-custom-foods',JSON.stringify(customCategoryFoods));queueCloudSave();openQuickCategory(activeQuickCategory);const toast=$('#toast');toast.textContent=`${name}を削除しました`;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200);return}const button=event.target.closest('[data-quick-food]');if(button)selectQuickFood(button.dataset.quickFood)};
$('#manageCustomFoods').onclick=()=>deletingCustomFood?openQuickCategory(activeQuickCategory):showCustomFoodDeleteMode();
$('#customFoodForm').onsubmit=event=>{event.preventDefault();const name=$('#customFoodName').value.trim();if(!name||!activeQuickCategory)return;const category=QUICK_CATEGORIES.find(item=>item.id===activeQuickCategory),foods=foodsForCategory(category);if(foods.some(food=>normalizeFoodText(food)===normalizeFoodText(name))){const toast=$('#toast');toast.textContent='同じ食材がすでにあります';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200);return}const categoryName={meat:'肉類',fish:'魚介類',vegetable:'野菜',fruit:'果物',dairy:'乳製品',daily:'乳製品・日配',seasoning:'調味料',frozen:'冷凍食品'}[activeQuickCategory]||'その他',perishable=['meat','fish'].includes(activeQuickCategory);customCategoryFoods[activeQuickCategory]=[...(customCategoryFoods[activeQuickCategory]||[]),name];localStorage.setItem('fridge-custom-foods',JSON.stringify(customCategoryFoods));saveFoodRule(name,categoryName,perishable?3:7,30,perishable?'消費期限':'賞味期限');queueCloudSave();$('#customFoodName').value='';openQuickCategory(activeQuickCategory);const toast=$('#toast');toast.textContent=`${name}を追加しました。期限設定ページで日数を変更できます`;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)};
$('#closeCategoryFoods').onclick=()=>$('#categoryFoodsPanel').hidden=true;$('#showManualEntry').onclick=()=>{$('#itemForm').scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>$('#itemName').focus(),350)};
function loadOcr(){if(globalThis.Tesseract)return Promise.resolve(globalThis.Tesseract);return new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';script.onload=()=>resolve(globalThis.Tesseract);script.onerror=reject;document.head.appendChild(script)})}
$('#itemName').oninput=()=>{const name=$('#itemName').value;applyFoodPreset(name);const rule=ruleFor(name);$('#itemExpiryKind').value=rule.expiryKind||(['肉類','魚介類'].includes(rule.category)?'消費期限':'保存目安')};$('#openState').onchange=()=>{if(currentStep===3)prepareFinalStep()};$('#foodSuggestions').innerHTML=FOOD_PRESETS.map(food=>`<option value="${food.name}"></option>`).join('');

function stopBarcode(){clearInterval(barcodeTimer);barcodeTimer=null;barcodeControls?.stop?.();barcodeControls=null;barcodeStream?.getTracks().forEach(track=>track.stop());barcodeStream=null;$('#barcodeVideo').srcObject=null}
function loadBarcodeReader(){if(globalThis.ZXingBrowser)return Promise.resolve(globalThis.ZXingBrowser);return new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/@zxing/browser@0.1.5/umd/zxing-browser.min.js';script.onload=()=>resolve(globalThis.ZXingBrowser);script.onerror=reject;document.head.appendChild(script)})}
function saveBarcodeProduct(code,name){barcodeCache[code]={name,updatedAt:new Date().toISOString()};localStorage.setItem('fridge-barcode-cache',JSON.stringify(barcodeCache));queueCloudSave()}
function showBarcodeExpiryStep(code,name,cached=false){stopBarcode();pendingBarcode=code;$('#barcodeScanStep').hidden=true;$('#barcodeExpiryStep').hidden=false;$('#barcodeProductName').value=name||'';$('#barcodeExpiryDate').value='';$('#expiryDateCandidates').innerHTML='';$('#barcodeStatus').textContent=cached?'端末に保存された商品情報を使用しました。':code?'商品を確認し、続けて期限表示を読み取ってください。':'入力した食材の期限表示を読み取ってください。';startExpiryCamera()}
function useBarcodeProduct(code,name,cached=false){saveBarcodeProduct(code,name);showBarcodeExpiryStep(code,name,cached)}
async function lookupBarcode(code){const digits=String(code||'').replace(/\D/g,'');$('#manualBarcodeProduct').hidden=true;if(!/^\d{8,14}$/.test(digits)){$('#barcodeStatus').textContent='8〜14桁のバーコード番号を入力してください。';return}$('#barcodeValue').value=digits;if(!/^(45|49)/.test(digits)){$('#barcodeStatus').textContent='海外製品のバーコードは対象外です。日本向けJANコード（45または49から始まる商品）のみ追加できます。';return}if(barcodeCache[digits]?.name){useBarcodeProduct(digits,barcodeCache[digits].name,true);return}$('#barcodeStatus').textContent='国内商品の情報を検索しています…';try{const response=await fetch(`https://jp.openfoodfacts.org/api/v2/product/${digits}.json?fields=product_name,product_name_ja,quantity`);const data=await response.json();const name=data.product?.product_name_ja||data.product?.product_name;if(data.status===1&&name){useBarcodeProduct(digits,name)}else{pendingBarcode=digits;$('#barcodeStatus').textContent=`国内商品データベースに未登録です。JAN ${digits} の商品名を一度入力すると、次回から端末の記録を使います。`;$('#manualBarcodeProduct').hidden=false}}catch{$('#barcodeStatus').textContent='商品検索に接続できませんでした。番号を確認してもう一度お試しください。'}}
async function openBarcode(){const dialog=$('#barcodeDialog');dialog.showModal();$('#barcodeStatus').textContent='カメラを準備しています。';if(!globalThis.isSecureContext||!navigator.mediaDevices?.getUserMedia){$('#barcodeStatus').textContent='カメラを利用できません。JANコードを手入力してください。';return}const video=$('#barcodeVideo');try{if('BarcodeDetector'in globalThis){barcodeStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});video.srcObject=barcodeStream;await video.play();const detector=new BarcodeDetector({formats:['ean_13','ean_8','upc_a','upc_e']});$('#barcodeStatus').textContent='バーコードを枠内に合わせてください。';barcodeTimer=setInterval(async()=>{if(video.readyState<2)return;try{const codes=await detector.detect(video);if(codes[0]){clearInterval(barcodeTimer);await lookupBarcode(codes[0].rawValue)}}catch{}},450)}else{const ZXingBrowser=await loadBarcodeReader();const reader=new ZXingBrowser.BrowserMultiFormatReader();$('#barcodeStatus').textContent='バーコードを枠内に合わせてください。';barcodeControls=await reader.decodeFromVideoDevice(undefined,video,(result)=>{if(result){barcodeControls?.stop();lookupBarcode(result.getText())}})}}catch{$('#barcodeStatus').textContent='自動読取を開始できません。JANコードを手入力してください。'}}
function extractExpiryDates(text){const dates=new Set(),now=new Date(),maxYear=now.getFullYear()+10;for(const match of text.matchAll(/(20\d{2}|\d{2})\s*[年\/\.\-]\s*(\d{1,2})\s*[月\/\.\-]\s*(\d{1,2})\s*日?/g)){let year=Number(match[1]);if(year<100)year+=2000;const month=Number(match[2]),day=Number(match[3]),date=new Date(year,month-1,day);if(date.getFullYear()===year&&date.getMonth()===month-1&&date.getDate()===day&&year<=maxYear)dates.add(iso(date))}return[...dates].sort()}
function stopExpiryCamera(){expiryStream?.getTracks().forEach(track=>track.stop());expiryStream=null;$('#expiryVideo').srcObject=null}
async function startExpiryCamera(){stopExpiryCamera();$('#expiryCameraButton').disabled=true;$('#expiryCameraButton').textContent='カメラを準備中…';$('#expiryOcrStatus').textContent='期限表示へカメラを向けてください。';try{expiryStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});const video=$('#expiryVideo');video.srcObject=expiryStream;await video.play();$('#expiryCameraButton').disabled=false;$('#expiryCameraButton').textContent='期限を読み取る';$('#expiryOcrStatus').textContent='期限表示を枠内に合わせて「期限を読み取る」を押してください。'}catch{$('#expiryCameraButton').textContent='カメラを利用できません';$('#expiryOcrStatus').textContent='カメラを起動できません。下の日付欄へ手入力してください。'}}
function captureExpiryFrame(){const video=$('#expiryVideo'),canvas=$('#expiryCanvas');if(!video.videoWidth){$('#expiryOcrStatus').textContent='カメラの準備ができていません。';return}canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0);$('#expiryCameraButton').disabled=true;canvas.toBlob(blob=>{if(blob)readExpiryImage(blob);else $('#expiryOcrStatus').textContent='映像を取得できませんでした。もう一度お試しください。'},'image/jpeg',.92)}
async function readExpiryImage(blob){const url=URL.createObjectURL(blob);$('#expiryDateCandidates').innerHTML='';$('#expiryOcrStatus').textContent='期限の文字認識を準備しています…';try{const Tesseract=await loadOcr();const result=await Tesseract.recognize(url,'jpn+eng',{logger:progress=>{if(progress.status==='recognizing text')$('#expiryOcrStatus').textContent=`期限を読み取り中… ${Math.round(progress.progress*100)}%`}});const dates=extractExpiryDates(result.data.text);if(dates.length){$('#barcodeExpiryDate').value=dates[0];$('#expiryOcrStatus').textContent=dates.length===1?'日付を読み取りました。正しいか確認してください。':'複数の日付を読み取りました。正しい期限を選んでください。';$('#expiryDateCandidates').innerHTML=dates.map(date=>`<button type="button" class="candidate expiry-date-option" data-date="${date}">${date}</button>`).join('');$$('.expiry-date-option').forEach(button=>button.onclick=()=>{$('#barcodeExpiryDate').value=button.dataset.date;$$('.expiry-date-option').forEach(option=>option.classList.toggle('selected',option===button))})}else $('#expiryOcrStatus').textContent='日付を認識できませんでした。もう一度読み取るか、日付欄へ手入力してください。'}catch{$('#expiryOcrStatus').textContent='期限を読み取れませんでした。もう一度読み取るか、日付欄へ手入力してください。'}finally{stopExpiryCamera();$('#expiryCameraButton').disabled=false;$('#expiryCameraButton').textContent='もう一度読み取る';setTimeout(()=>URL.revokeObjectURL(url),1000)}}
function continueBarcodeProduct(){const name=$('#barcodeProductName').value.trim();if(!name){$('#expiryOcrStatus').textContent='商品名を入力してください。';$('#barcodeProductName').focus();return}if(pendingBarcode)saveBarcodeProduct(pendingBarcode,name);pendingExpiryDate=$('#barcodeExpiryDate').value;pendingExpiryKind=$('#expiryKind').value;stopBarcode();stopExpiryCamera();$('#barcodeDialog').close();if(!pendingBarcode){if(pendingExpiryDate)$('#expiryDate').value=pendingExpiryDate;$('#expiryHint').textContent=`読み取った${pendingExpiryKind||'期限'}です。日付を再確認してください。`;return}$('#itemName').value=name;applyFoodPreset(name);navigate('add');showStep(1);const toast=$('#toast');toast.textContent='商品と期限を確認しました。保存場所を設定してください';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
function cancelBarcodeFlow(){stopBarcode();stopExpiryCamera();pendingBarcode='';pendingExpiryDate='';pendingExpiryKind=''}
$('#barcodeButton').onclick=()=>{$('#barcodeDialogEyebrow').textContent='JAN / EAN';$('#barcodeDialogTitle').textContent='バーコードで追加';$('#manualBarcodeProduct').hidden=true;$('#barcodeScanStep').hidden=false;$('#barcodeExpiryStep').hidden=true;$('#expiryDateCandidates').innerHTML='';openBarcode()};$('#manualExpiryButton').onclick=()=>{const name=$('#itemName').value.trim();if(!name){$('#itemName').reportValidity();return}pendingExpiryDate='';pendingExpiryKind='';const category=ruleFor(name).category;$('#expiryKind').value=['肉類','魚介類'].includes(category)?'消費期限':'賞味期限';$('#barcodeDialogEyebrow').textContent='EXPIRY OCR';$('#barcodeDialogTitle').textContent='期限を読み取る';$('#barcodeDialog').showModal();showBarcodeExpiryStep('',name)};$('#closeBarcode').onclick=()=>{$('#barcodeDialog').close();cancelBarcodeFlow()};$('#barcodeDialog').addEventListener('cancel',cancelBarcodeFlow);$('#lookupBarcode').onclick=()=>lookupBarcode($('#barcodeValue').value);$('#barcodeValue').onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();lookupBarcode(event.target.value)}};$('#manualBarcodeProduct').onclick=()=>showBarcodeExpiryStep(pendingBarcode,'');$('#expiryCameraButton').onclick=()=>expiryStream?captureExpiryFrame():startExpiryCamera();$('#confirmBarcodeProduct').onclick=continueBarcodeProduct;
function setSignedOutState(clearLocal=true){currentCloudUser=null;if(clearLocal){items=[];customCategoryFoods={};barcodeCache={};localStorage.removeItem('fridge-items');localStorage.removeItem('fridge-custom-foods');localStorage.removeItem('fridge-barcode-cache');$('#itemCount').textContent='0';render();renderQuickPicker()}$('#signOutButton').hidden=true;$('#cloudModeBadge').textContent='ログイン待ち';$('#authGate').hidden=false}
async function loadCloudUserData(user){currentCloudUser=user;$('#authGate').hidden=true;$('#signOutButton').hidden=false;$('#cloudModeBadge').textContent='同期中';const{data,error}=await cloudClient.from('fridge_user_data').select('items,custom_foods,barcode_cache').eq('user_id',user.id).maybeSingle();if(error){$('#cloudModeBadge').textContent='同期エラー';$('#authStatus').textContent='データを開けませんでした。SupabaseのテーブルとRLS設定を確認してください。';console.error(error);return}if(data){applyingCloudData=true;items=Array.isArray(data.items)?data.items:[];customCategoryFoods=data.custom_foods&&typeof data.custom_foods==='object'?data.custom_foods:{};barcodeCache=data.barcode_cache&&typeof data.barcode_cache==='object'?data.barcode_cache:{};storeLocalState();applyingCloudData=false;render();renderQuickPicker();$('#cloudModeBadge').textContent='同期済み'}else{await persistCloudState()}}
function loadSupabaseLibrary(){if(globalThis.supabase?.createClient)return Promise.resolve();return new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';script.onload=resolve;script.onerror=reject;document.head.appendChild(script)})}
async function initializeCloudMode(){if(!cloudConfigured){$('#cloudModeBadge').textContent='端末保存';return}try{await loadSupabaseLibrary()}catch{$('#authGate').hidden=false;$('#authStatus').textContent='ログイン機能を読み込めませんでした。通信状態を確認してください。';return}cloudClient=globalThis.supabase.createClient(cloudConfig.supabaseUrl,cloudConfig.supabaseAnonKey);const{data:{session}}=await cloudClient.auth.getSession();if(session?.user)await loadCloudUserData(session.user);else setSignedOutState(false);cloudClient.auth.onAuthStateChange((event,session)=>{setTimeout(()=>{if(session?.user)loadCloudUserData(session.user);else if(event==='SIGNED_OUT')setSignedOutState()},0)})}
$('#magicLinkForm').onsubmit=async event=>{event.preventDefault();if(!cloudClient)return;const email=$('#authEmail').value.trim();$('#authStatus').textContent='ログインメールを送信しています…';const redirectTo=location.origin+location.pathname;const{error}=await cloudClient.auth.signInWithOtp({email,options:{emailRedirectTo:redirectTo}});$('#authStatus').textContent=error?`送信できませんでした：${error.message}`:'メールを送信しました。同じ端末でリンクを開いてください。'};
$('#signOutButton').onclick=async()=>{if(cloudClient&&confirm('ログアウトしますか？ この端末の表示データも消去します。'))await cloudClient.auth.signOut()};
function editableRules(){const custom=JSON.parse(localStorage.getItem('fridge-food-rules')||'{}');const base=DEFAULT_RULES.flatMap(rule=>rule.words.map(name=>({name,category:rule.category,cold:rule.cold,frozen:rule.frozen,builtIn:true})));return[...base,...Object.values(custom).map(rule=>({name:rule.words[0],...rule,builtIn:false}))].filter((item,index,list)=>list.findIndex(x=>normalizeFoodText(x.name)===normalizeFoodText(item.name))===index)}
const CATEGORY_IDS={'肉類':'meat','魚介類':'fish','野菜':'vegetable','果物':'fruit','乳製品・日配':'daily','乳製品':'dairy','卵':'daily','調味料':'seasoning','冷凍食品':'frozen','その他':'other'};
function renderFoodSettings(){const query=$('#foodSettingsSearch').value.trim().toLowerCase();const rows=editableRules().filter(x=>x.name.toLowerCase().includes(query));$('#foodSettingsList').innerHTML=rows.map(item=>`<article class="settings-card food-setting-row" data-food-setting="${item.name}"><div><b>${item.name}</b><small>${item.category}</small></div><select data-expiry-kind><option ${item.expiryKind==='賞味期限'?'selected':''}>賞味期限</option><option ${item.expiryKind==='消費期限'?'selected':''}>消費期限</option></select><label>冷蔵<input type="number" min="1" max="365" value="${item.cold}" data-days="cold">日</label><label>冷凍<input type="number" min="1" max="730" value="${item.frozen}" data-days="frozen">日</label><button type="button" class="secondary save-food-setting">保存</button>${item.builtIn?'':`<button type="button" class="text-button delete-food-setting">削除</button>`}</article>`).join('')||'<div class="empty">該当する食材がありません。</div>'}
function addFoodToCategory(name,category){const id=CATEGORY_IDS[category]||'daily';if(!(customCategoryFoods[id]||[]).some(food=>normalizeFoodText(food)===normalizeFoodText(name)))customCategoryFoods[id]=[...(customCategoryFoods[id]||[]),name];localStorage.setItem('fridge-custom-foods',JSON.stringify(customCategoryFoods));renderQuickPicker()}
function saveFoodRule(name,category,cold,frozen,expiryKind='賞味期限'){const custom=JSON.parse(localStorage.getItem('fridge-food-rules')||'{}');custom[normalizeFoodText(name)]={words:[name],category,cold:Number(cold),frozen:Number(frozen),expiryKind};localStorage.setItem('fridge-food-rules',JSON.stringify(custom));RULES=[...Object.values(custom),...DEFAULT_RULES];addFoodToCategory(name,category);renderFoodSettings()}
$('#foodSettingsSearch').oninput=renderFoodSettings;$('#foodSettingsList').onclick=event=>{const row=event.target.closest('[data-food-setting]');if(!row)return;const name=row.dataset.foodSetting,existing=editableRules().find(x=>x.name===name);if(event.target.closest('.save-food-setting'))saveFoodRule(name,existing.category,row.querySelector('[data-days="cold"]').value,row.querySelector('[data-days="frozen"]').value,row.querySelector('[data-expiry-kind]').value);if(event.target.closest('.delete-food-setting')&&confirm(`「${name}」を削除しますか？`)){const custom=JSON.parse(localStorage.getItem('fridge-food-rules')||'{}');delete custom[normalizeFoodText(name)];localStorage.setItem('fridge-food-rules',JSON.stringify(custom));RULES=[...Object.values(custom),...DEFAULT_RULES];renderFoodSettings()}};
$('#addFoodSettingForm').onsubmit=event=>{event.preventDefault();saveFoodRule($('#newFoodName').value.trim(),$('#newFoodCategory').value,$('#newFoodCold').value,$('#newFoodFrozen').value,$('#newFoodExpiryKind').value);event.target.reset();$('#newFoodCold').value=7;$('#newFoodFrozen').value=30};
function roomEditor(room){return`<div class="room-setting-row" data-room-id="${room.id}"><input data-room-name value="${room.name}" maxlength="30" aria-label="区画名"><select data-room-storage><option ${room.storage==='冷蔵'?'selected':''}>冷蔵</option><option ${room.storage==='冷凍'?'selected':''}>冷凍</option></select><label><input data-room-capacity type="number" min="1" max="1000" value="${room.capacity}">L</label><button type="button" class="text-button delete-room">削除</button></div>`}
function previewFridgeRooms(rooms){const preview=$('#fridgeSettingsPreview');preview.className='whole-fridge-choice fridge-preview-unified';preview.innerHTML=rooms.map(room=>`<div class="preview-room room-${room.id} ${room.storage==='冷凍'?'frozen':''}"><b>${room.name}</b><small>${room.storage}・${room.capacity}L</small></div>`).join('');$('#fridgeTotalPreview').textContent=`合計容量：${rooms.reduce((sum,room)=>sum+Number(room.capacity||0),0)}L`}
function draftFridgeRooms(){return $$('.room-setting-row').map((row,index)=>({id:row.dataset.roomId||`draft-${index}`,name:row.querySelector('[data-room-name]').value.trim()||`区画${index+1}`,storage:row.querySelector('[data-room-storage]').value,capacity:Number(row.querySelector('[data-room-capacity]').value)||0}))}
function renderFridgeSettings(){const rows=FRIDGE.locations.map(roomEditor);$('#fridgeRoomSettings').innerHTML=rows.join('');previewFridgeRooms(FRIDGE.locations)}
function saveFridgeLayout(){const locations=$$('.room-setting-row').map((row,index)=>({id:row.dataset.roomId||`room-${Date.now()}-${index}`,name:row.querySelector('[data-room-name]').value.trim()||`区画${index+1}`,storage:row.querySelector('[data-room-storage]').value,capacity:Number(row.querySelector('[data-room-capacity]').value)||1}));if(!locations.some(room=>room.storage==='冷蔵')||!locations.some(room=>room.storage==='冷凍')){alert('冷蔵区画と冷凍区画を1つ以上設定してください。');return}FRIDGE={model:'マイ冷蔵庫',locations,totalLiters:locations.reduce((sum,room)=>sum+room.capacity,0)};localStorage.setItem('fridge-profile',JSON.stringify(FRIDGE));document.querySelector('.brand small').textContent=`カスタム / ${FRIDGE.totalLiters}L`;refreshLocationSelectors();renderFridgeSettings();render()}
function refreshLocationSelectors(){$('#filterLocation').innerHTML='<option value="">すべての場所</option>'+FRIDGE.locations.map(x=>`<option value="${x.id}">${x.name}</option>`).join('');$('#editLocation').innerHTML=FRIDGE.locations.map(x=>`<option value="${x.id}">${x.name}</option>`).join('')}
$('#fridgeRoomSettings').oninput=()=>previewFridgeRooms(draftFridgeRooms());$('#fridgeRoomSettings').onchange=()=>previewFridgeRooms(draftFridgeRooms());
$('#addFridgeRoom').onclick=()=>{FRIDGE.locations.push({id:`room-${Date.now()}`,name:'新しい区画',storage:'冷蔵',capacity:30});renderFridgeSettings()};$('#fridgeRoomSettings').onclick=event=>{const row=event.target.closest('.room-setting-row');if(event.target.closest('.delete-room')&&row&&FRIDGE.locations.length>2&&confirm('この区画を削除しますか？')){FRIDGE.locations=FRIDGE.locations.filter(room=>room.id!==row.dataset.roomId);renderFridgeSettings()}};$('#saveFridgeSettings').onclick=saveFridgeLayout;$('#resetFridgeSettings').onclick=()=>{if(confirm('初期レイアウトへ戻しますか？')){FRIDGE=JSON.parse(JSON.stringify(DEFAULT_FRIDGE));FRIDGE.totalLiters=517;renderFridgeSettings()}};
$('#purchaseDate').value=iso(new Date());$('#today').textContent=new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'long',day:'numeric',weekday:'short'}).format(new Date());$('#filterLocation').innerHTML+=FRIDGE.locations.map(x=>`<option value="${x.id}">${x.name}</option>`).join('');renderQuickPicker();refreshStoredItems();window.addEventListener('pageshow',refreshStoredItems);window.addEventListener('focus',refreshStoredItems);window.addEventListener('storage',event=>{if(event.key==='fridge-items')refreshStoredItems()});
refreshLocationSelectors();document.querySelector('.brand small').textContent=`カスタム / ${FRIDGE.totalLiters}L`;initializeCloudMode();
if('serviceWorker' in navigator&&location.protocol.startsWith('http'))window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
